export default {
    fr: {
        'Log in': 'Se connecter',
        'Welcome back': 'Bon retour',
        'Log in to continue': 'Connectez-vous pour continuer',
        Email: 'E-mail',
        Password: 'Mot de passe',
        'Remember me': 'Se souvenir de moi',
        'Forgot password?': 'Mot de passe oublié ?',
        'Signing you in...': 'Connexion en cours...',
        'LOG IN': 'SE CONNECTER',
        'Authenticating...': 'Authentification...',
        "Don't have an account?": 'Vous n’avez pas de compte ?',
        Register: 'Inscription',
        'Checking credentials...': 'Vérification des identifiants...',
        'Authenticating session...': 'Authentification de la session...',
        'Redirecting to dashboard...': 'Redirection vers le tableau de bord...',
        'Create Account': 'Créer un compte',
        'Join Ituze QR Ltd to manage your properties': 'Rejoignez Ituze QR Ltd pour gérer vos biens',
        'First Name': 'Prénom',
        'Last Name': 'Nom',
        'Enter a valid email address': 'Saisissez une adresse e-mail valide',
        'Phone Number': 'Numéro de téléphone',
        ':network number detected': 'Numéro :network détecté',
        'Enter a valid 10-digit Rwanda mobile number (072, 073, 078, or 079)': 'Saisissez un numéro de téléphone mobile rwandais valide à 10 chiffres (072, 073, 078 ou 079)',
        'Confirm Password': 'Confirmer le mot de passe',
        'Passwords do not match': 'Les mots de passe ne correspondent pas',
        'Password strength': 'Robustesse du mot de passe',
        'Very weak': 'Très faible',
        Weak: 'Faible',
        Good: 'Bon',
        Strong: 'Fort',
        'Use at least 8 characters with upper/lowercase, numbers, and symbols.': 'Utilisez au moins 8 caractères avec majuscules, minuscules, chiffres et symboles.',
        'CREATING ACCOUNT...': 'CRÉATION DU COMPTE...',
        REGISTER: 'S’INSCRIRE',
        'Fill in all fields correctly to continue': 'Remplissez correctement tous les champs pour continuer',
        'Already have an account?': 'Vous avez déjà un compte ?',
        Login: 'Connexion',
        'Forgot Password': 'Mot de passe oublié',
        'Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.': 'Vous avez oublié votre mot de passe ? Aucun problème. Indiquez votre adresse e-mail et nous vous enverrons un lien pour en choisir un nouveau.',
        'Email Password Reset Link': 'Envoyer le lien de réinitialisation',
        'This is a secure area of the application. Please confirm your password before continuing.': 'Cette zone de l’application est sécurisée. Veuillez confirmer votre mot de passe avant de continuer.',
        Confirm: 'Confirmer',
        'Reset Password': 'Réinitialiser le mot de passe',
        'Verify Your Email': 'Vérifiez votre e-mail',
        'Enter your verification code': 'Saisissez votre code de vérification',
        "We've sent a 6-digit code to": 'Nous avons envoyé un code à 6 chiffres à',
        'A new code has been sent to :email.': 'Un nouveau code a été envoyé à :email.',
        'Verify Code': 'Vérifier le code',
        'Development only': 'Développement uniquement',
        'No real email is sent locally. Use this code to test, or skip verification below.': 'Aucun e-mail réel n’est envoyé en local. Utilisez ce code pour tester ou ignorez la vérification ci-dessous.',
        'Click Resend Code to generate a test code.': 'Cliquez sur Renvoyer le code pour en générer un de test.',
        'Dev: Verify Instantly': 'Développement : vérifier immédiatement',
        'Resend Code': 'Renvoyer le code',
        'Account status': 'Statut du compte',
        'Your account was not approved': 'Votre compte n’a pas été approuvé',
        'Your subscription has expired': 'Votre abonnement a expiré',
        'Welcome to Ituze-Qra Ltd': 'Bienvenue chez Ituze-Qra Ltd',
        'Please contact Ituze-Qra Ltd for help with your account.': 'Veuillez contacter Ituze-Qra Ltd pour obtenir de l’aide concernant votre compte.',
        'Your owner subscription has ended. Please contact Ituze-Qra Ltd to renew access.': 'Votre abonnement propriétaire a pris fin. Contactez Ituze-Qra Ltd pour renouveler votre accès.',
        'Welcome to Ituze-Qra Ltd web app. Our team is checking and your account will be available in less than 5 minutes.': 'Bienvenue sur l’application web Ituze-Qra Ltd. Notre équipe vérifie votre compte, qui sera disponible dans moins de 5 minutes.',
        'Your one-year subscription begins on the day an administrator approves your account.': 'Votre abonnement d’un an commence le jour où un administrateur approuve votre compte.',
        'Log out': 'Déconnexion',
        'Profile Information': 'Informations du profil',
        'Update your contact details, identity, location, and profile photo.': 'Mettez à jour vos coordonnées, votre identité, votre lieu de résidence et votre photo de profil.',
        'Phone number': 'Numéro de téléphone',
        'Identity document': 'Pièce d’identité',
        'NIDA / passport number': 'Numéro NIDA / passeport',
        'Street address': 'Adresse postale',
        Sector: 'Secteur',
        'Select sector': 'Sélectionnez un secteur',
        'Profile photo (optional)': 'Photo de profil (facultatif)',
        'Current profile': 'Profil actuel',
        'Your email address is unverified.': 'Votre adresse e-mail n’est pas vérifiée.',
        'Click here to re-send the verification email.': 'Cliquez ici pour renvoyer l’e-mail de vérification.',
        'A new verification link has been sent to your email address.': 'Un nouveau lien de vérification a été envoyé à votre adresse e-mail.',
        Save: 'Enregistrer',
        'Saved.': 'Enregistré.',
        'Update Password': 'Mettre à jour le mot de passe',
        'Ensure your account is using a long, random password to stay secure.': 'Utilisez un mot de passe long et aléatoire pour sécuriser votre compte.',
        'Current Password': 'Mot de passe actuel',
        'New Password': 'Nouveau mot de passe',
        'Delete Account': 'Supprimer le compte',
        'Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.': 'Une fois votre compte supprimé, toutes ses ressources et données seront définitivement effacées. Téléchargez les informations que vous souhaitez conserver avant de supprimer votre compte.',
        'Are you sure you want to delete your account?': 'Voulez-vous vraiment supprimer votre compte ?',
        'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.': 'Une fois votre compte supprimé, toutes ses ressources et données seront définitivement effacées. Saisissez votre mot de passe pour confirmer la suppression définitive.',
        'Pending Approvals': 'Approbations en attente',
        'Saving…': 'Enregistrement…',
        'No accounts waiting for approval right now.': 'Aucun compte en attente d’approbation.',
        'Email verified · Profile complete': 'E-mail vérifié · Profil complet',
        Approve: 'Approuver',
        Reject: 'Rejeter',
        'Approve this account?': 'Approuver ce compte ?',
        'Reject this account?': 'Rejeter ce compte ?',
        'Confirm that payment was verified outside the app. :name will then be approved, and their one-year subscription will start today.': 'Confirmez que le paiement a été vérifié en dehors de l’application. :name sera alors approuvé et son abonnement d’un an commencera aujourd’hui.',
        ':name will not be able to access the dashboard. You can reconsider this later.': ':name ne pourra pas accéder au tableau de bord. Vous pourrez revenir sur cette décision plus tard.',
        'Yes, Approve': 'Oui, approuver',
        'Yes, Reject': 'Oui, rejeter',
        NIDA: 'NIDA',
    },
    rw: {
        'Log in': 'Injira',
        'Welcome back': 'Urahawe ikaze',
        'Log in to continue': 'Injira kugira ngo ukomeze',
        Email: 'Imeyili',
        Password: 'Ijambo ry’ibanga',
        'Remember me': 'Nyibuka',
        'Forgot password?': 'Wibagiwe ijambo ry’ibanga?',
        'Signing you in...': 'Turimo kukwinjiza...',
        'LOG IN': 'INJIRA',
        'Authenticating...': 'Turimo kugenzura...',
        "Don't have an account?": 'Nta konti ufite?',
        Register: 'Iyandikishe',
        'Checking credentials...': 'Turimo kugenzura amakuru...',
        'Authenticating session...': 'Turimo kugenzura konti...',
        'Redirecting to dashboard...': 'Turimo kukujyana ku rubuga rw’ibanze...',
        'Create Account': 'Fungura konti',
        'Join Ituze QR Ltd to manage your properties': 'Injira muri Ituze QR Ltd kugira ngo ucunge inzu zawe',
        'First Name': 'Izina',
        'Last Name': 'Izina ry’umuryango',
        'Enter a valid email address': 'Andika imeyili yemewe',
        'Phone Number': 'Nomero ya telefoni',
        ':network number detected': 'Nomero ya :network yamenyekanye',
        'Enter a valid 10-digit Rwanda mobile number (072, 073, 078, or 079)': 'Andika nomero ya telefoni yo mu Rwanda y’imibare 10 yemewe (072, 073, 078 cyangwa 079)',
        'Confirm Password': 'Ongera wandike ijambo ry’ibanga',
        'Passwords do not match': 'Amagambo y’ibanga ntahura',
        'Password strength': 'Imbaraga z’ijambo ry’ibanga',
        'Very weak': 'Ryoroshye cyane',
        Weak: 'Ryoroshye',
        Good: 'Ni ryiza',
        Strong: 'Rikomeye',
        'Use at least 8 characters with upper/lowercase, numbers, and symbols.': 'Koresha nibura inyuguti 8 zirimo inyuguti nkuru n’intoya, imibare n’ibimenyetso.',
        'CREATING ACCOUNT...': 'TURIMO GUKORA KONTI...',
        REGISTER: 'IYANDIKISHE',
        'Fill in all fields correctly to continue': 'Uzuza neza ahantu hose kugira ngo ukomeze',
        'Already have an account?': 'Usanzwe ufite konti?',
        Login: 'Injira',
        'Forgot Password': 'Wibagiwe ijambo ry’ibanga',
        'Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.': 'Wibagiwe ijambo ry’ibanga? Tubwire imeyili yawe, turayikoherereza umurongo wo gushyiraho irindi jambo ry’ibanga.',
        'Email Password Reset Link': 'Ohereza umurongo wo guhindura ijambo ry’ibanga',
        'This is a secure area of the application. Please confirm your password before continuing.': 'Aha ni ahantu harinzwe. Emeza ijambo ry’ibanga mbere yo gukomeza.',
        Confirm: 'Emeza',
        'Reset Password': 'Hindura ijambo ry’ibanga',
        'Verify Your Email': 'Emeza imeyili yawe',
        'Enter your verification code': 'Andika kode yo kwemeza',
        "We've sent a 6-digit code to": 'Twohereje kode y’imibare 6 kuri',
        'A new code has been sent to :email.': 'Kode nshya yoherejwe kuri :email.',
        'Verify Code': 'Emeza kode',
        'Development only': 'Ikoreshwa mu igerageza gusa',
        'No real email is sent locally. Use this code to test, or skip verification below.': 'Nta imeyili nyayo yoherejwe muri mudasobwa yawe. Koresha iyi kode mu igerageza cyangwa usimbuke kwemeza.',
        'Click Resend Code to generate a test code.': 'Kanda Ohereza kode bushya kugira ngo ubone kode yo kugerageza.',
        'Dev: Verify Instantly': 'Igerageza: Emeza nonaha',
        'Resend Code': 'Ongera wohereze kode',
        'Account status': 'Imimerere ya konti',
        'Your account was not approved': 'Konti yawe ntiyemewe',
        'Your subscription has expired': 'Igihe cyo kwiyandikisha cyarangiye',
        'Welcome to Ituze-Qra Ltd': 'Murakaza neza muri Ituze-Qra Ltd',
        'Please contact Ituze-Qra Ltd for help with your account.': 'Vugana na Ituze-Qra Ltd bagufashe kuri konti yawe.',
        'Your owner subscription has ended. Please contact Ituze-Qra Ltd to renew access.': 'Igihe cyo gukoresha konti ya nyir’inzu cyarangiye. Vugana na Ituze-Qra Ltd wongere uyikoreshe.',
        'Welcome to Ituze-Qra Ltd web app. Our team is checking and your account will be available in less than 5 minutes.': 'Murakaza neza muri porogaramu ya Ituze-Qra Ltd. Itsinda ryacu ririmo kugenzura konti yawe, izatangira gukora mu minota itarenze itanu.',
        'Your one-year subscription begins on the day an administrator approves your account.': 'Igihe cyawe cy’umwaka gitangira ku munsi umuyobozi yemeje konti yawe.',
        'Log out': 'Sohoka',
        'Profile Information': 'Amakuru y’umwirondoro',
        'Update your contact details, identity, location, and profile photo.': 'Hindura amakuru y’itumanaho, indangamuntu, aho utuye n’ifoto yawe.',
        'Phone number': 'Nomero ya telefoni',
        'Identity document': 'Inyandiko y’irangamuntu',
        'NIDA / passport number': 'Nomero y’indangamuntu / pasiporo',
        'Street address': 'Aderesi y’umuhanda',
        Sector: 'Umurenge',
        'Select sector': 'Hitamo umurenge',
        'Profile photo (optional)': 'Ifoto y’umwirondoro (si ngombwa)',
        'Current profile': 'Umwirondoro uriho ubu',
        'Your email address is unverified.': 'Aderesi ya imeyili yawe ntiyemejwe.',
        'Click here to re-send the verification email.': 'Kanda aha wongere wohereze imeyili yo kwemeza.',
        'A new verification link has been sent to your email address.': 'Umurongo mushya wo kwemeza woherejwe kuri imeyili yawe.',
        Save: 'Bika',
        'Saved.': 'Byabitswe.',
        'Update Password': 'Hindura ijambo ry’ibanga',
        'Ensure your account is using a long, random password to stay secure.': 'Koresha ijambo ry’ibanga rirerire kandi rigoye kugira ngo urinde konti yawe.',
        'Current Password': 'Ijambo ry’ibanga ukoresha',
        'New Password': 'Ijambo ry’ibanga rishya',
        'Delete Account': 'Siba konti',
        'Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.': 'Iyo konti yawe imaze gusibwa, amakuru yayo yose arasibwa burundu. Banza ubike ibyo ushaka kugumana.',
        'Are you sure you want to delete your account?': 'Uremeza ko ushaka gusiba konti yawe?',
        'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.': 'Iyo konti yawe imaze gusibwa, amakuru yayo yose arasibwa burundu. Andika ijambo ry’ibanga wemeze ko ushaka kuyisiba burundu.',
        'Pending Approvals': 'Konti zitegereje kwemezwa',
        'Saving…': 'Birabikwa...',
        'No accounts waiting for approval right now.': 'Nta konti itegereje kwemezwa ubu.',
        'Email verified · Profile complete': 'Imeyili yemejwe · Umwirondoro uruzuye',
        Approve: 'Emeza',
        Reject: 'Anga',
        'Approve this account?': 'Wemeze iyi konti?',
        'Reject this account?': 'Urahakana iyi konti?',
        'Confirm that payment was verified outside the app. :name will then be approved, and their one-year subscription will start today.': 'Emeza ko ubwishyu bwagenzuwe hanze ya porogaramu. :name azemererwa kandi igihe cy’umwaka gitangire uyu munsi.',
        ':name will not be able to access the dashboard. You can reconsider this later.': ':name ntazemererwa gukoresha urubuga rw’ibanze. Ushobora kongera kubisuzuma nyuma.',
        'Yes, Approve': 'Yego, emera',
        'Yes, Reject': 'Yego, hana',
        NIDA: 'Indangamuntu',
    },
};
