export default {
    fr: {
        Dashboard: 'Tableau de bord',
        Properties: 'Propriétés',
        Tenants: 'Locataires',
        Leases: 'Baux',
        Payments: 'Paiements',
        Messages: 'Messages',
        Reports: 'Rapports',
        Approvals: 'Approbations',
        'All Users': 'Tous les utilisateurs',
        'Admin Access': 'Accès administrateur',
        'Signed in as': 'Connecté en tant que',
        Profile: 'Profil',
        'Log Out': 'Déconnexion',
        Success: 'Succès',
        Continue: 'Continuer',
        Support: 'Assistance',
        'Help center & FAQs': "Centre d'aide et FAQ",
        'Contact admin': "Contacter l'administrateur",
        'Live chat': 'Chat en direct',
        'Privacy Policy': 'Politique de confidentialité',
        'Terms of Service': "Conditions d'utilisation",
        'Contact Us': 'Nous contacter',
        'All rights reserved. Made for landlords and tenants across Rwanda':
            'Tous droits réservés. Conçu pour les propriétaires et locataires du Rwanda',
        'EN': 'Anglais',
        'FR': 'Français',
        'RW': 'Kinyarwanda',
        'Select language': 'Choisir la langue',
        English: 'Anglais',
        Login: 'Connexion',
        Register: 'Inscription',
        'All rights reserved.': 'Tous droits réservés.',
        Phone: 'Téléphone',
        Overview: 'Vue d’ensemble',
        'Good to see you, :name': 'Heureux de vous revoir, :name',
        'Here’s what’s happening across your portfolio.': 'Voici ce qui se passe dans votre portefeuille immobilier.',
        'Add property': 'Ajouter un bien',
        'Total units': 'Nombre total d’unités',
        'Occupied units': 'Unités occupées',
        'Available units': 'Unités disponibles',
        'Portfolio occupancy': 'Occupation du portefeuille',
        occupied: 'occupées',
        'available · :count under maintenance': 'disponibles · :count en maintenance',
        'Recent properties': 'Biens récents',
        'View all': 'Tout voir',
        'No properties yet.': 'Aucun bien pour le moment.',
        'Add your first property': 'Ajoutez votre premier bien',
        'Tenants & active leases': 'Locataires et baux actifs',
        'Current occupants, lease terms, and direct tenant records.': 'Occupants actuels, conditions de bail et dossiers des locataires.',
        'Open tenant directory': 'Ouvrir le répertoire des locataires',
        Tenant: 'Locataire',
        'Property / unit': 'Bien / unité',
        'Lease term': 'Durée du bail',
        Rent: 'Loyer',
        Status: 'Statut',
        Details: 'Détails',
        Active: 'Actif',
        'Open unit': 'Ouvrir l’unité',
        'No active tenants yet. Add a lease from a unit or assign a tenant from the tenant directory.':
            'Aucun locataire actif. Ajoutez un bail depuis une unité ou attribuez un locataire depuis le répertoire.',
        'Visitor inquiries': 'Demandes des visiteurs',
        'Contact the visitor, then mark the inquiry as read to allow a new inquiry for this property.':
            'Contactez le visiteur, puis marquez la demande comme lue pour autoriser une nouvelle demande pour ce bien.',
        New: 'Nouveau',
        Call: 'Appeler',
        'SMS visitor': 'Envoyer un SMS',
        Email: 'E-mail',
        'Mark as read': 'Marquer comme lu',
        'No visitor inquiries yet.': 'Aucune demande de visiteur pour le moment.',
        'Your account has expired': 'Votre compte a expiré',
        'Please contact support to renew access.': 'Veuillez contacter l’assistance pour renouveler votre accès.',
        'Tenant details': 'Détails du locataire',
        'Back to tenants': 'Retour aux locataires',
        'Company tenant': 'Locataire entreprise',
        'Individual tenant': 'Locataire particulier',
        'Close editor': 'Fermer la modification',
        'Edit tenant details': 'Modifier les informations du locataire',
        'Assign a unit': 'Attribuer une unité',
        'Tenant type': 'Type de locataire',
        Individual: 'Particulier',
        Company: 'Entreprise',
        'First name': 'Prénom',
        'Last name': 'Nom',
        'Company name': 'Nom de l’entreprise',
        'Registration number': 'Numéro d’enregistrement',
        'Company TIN': 'Numéro d’identification fiscale de l’entreprise',
        'Representative full name': 'Nom complet du représentant',
        'Save changes': 'Enregistrer les modifications',
        'Cancel': 'Annuler',
        'Create tenant': 'Créer un locataire',
        'Search tenants...': 'Rechercher des locataires...',
        'Manage the people and businesses occupying your units.': 'Gérez les personnes et entreprises occupant vos unités.',
        'No tenants found': 'Aucun locataire trouvé',
        'Try a different search.': 'Essayez une autre recherche.',
        'Tenants will appear here when assigned to a unit.': 'Les locataires apparaîtront ici lorsqu’ils seront attribués à une unité.',
        Unit: 'Unité',
        Payment: 'Paiement',
        'Your subscription ended on :date. Please contact support to renew access.': 'Votre abonnement a pris fin le :date. Veuillez contacter l’assistance pour renouveler votre accès.',
        Read: 'Lu',
        ':available available · :maintenance under maintenance': ':available disponibles · :maintenance en maintenance',
        'Portfolio reports': 'Rapports du portefeuille',
        ':occupied occupied of :total total units': ':occupied occupées sur :total unités au total',
    },
    rw: {
        Dashboard: 'Imbonerahamwe',
        Properties: 'Inzu',
        Tenants: 'Abakodesha',
        Leases: 'Amasezerano y’ubukode',
        Payments: 'Kwishyura',
        Messages: 'Ubutumwa',
        Reports: 'Raporo',
        Approvals: 'Ibyemezo',
        'All Users': 'Abakoresha bose',
        'Admin Access': 'Ubuyobozi',
        'Signed in as': 'Winjiye nka',
        Profile: 'Umwirondoro',
        'Log Out': 'Sohoka',
        Success: 'Byagenze neza',
        Continue: 'Komeza',
        Support: 'Ubufasha',
        'Help center & FAQs': 'Ubufasha n’ibisubizo ku bibazo',
        'Contact admin': 'Vugana n’ubuyobozi',
        'Live chat': 'Ubutumwa ako kanya',
        'Privacy Policy': 'Amabwiriza y’ibanga',
        'Terms of Service': 'Amabwiriza y’imikoreshereze',
        'Contact Us': 'Twandikire',
        'All rights reserved. Made for landlords and tenants across Rwanda':
            'Uburenganzira bwose burabitswe. Byagenewe abakodesha n’abakodeshwa mu Rwanda',
        EN: 'Icyongereza',
        FR: 'Igifaransa',
        RW: 'Ikinyarwanda',
        'Select language': 'Hitamo ururimi',
        English: 'Icyongereza',
        Login: 'Injira',
        Register: 'Iyandikishe',
        'All rights reserved.': 'Uburenganzira bwose burabitswe.',
        Phone: 'Telefoni',
        Overview: 'Incamake',
        'Good to see you, :name': 'Neza kukubona, :name',
        'Here’s what’s happening across your portfolio.': 'Dore ibiri kubera mu mitungo yawe.',
        'Add property': 'Ongeraho inzu',
        'Total units': 'Ibyumba byose',
        'Occupied units': 'Ibyumba bikodeshejwe',
        'Available units': 'Ibyumba bihari',
        'Portfolio occupancy': 'Imikoreshereze y’imitungo',
        occupied: 'birakodeshejwe',
        'available · :count under maintenance': 'birahari · :count biri gusanwa',
        'Recent properties': 'Inzu ziheruka',
        'View all': 'Reba byose',
        'No properties yet.': 'Nta nzu zirahari.',
        'Add your first property': 'Ongeraho inzu ya mbere',
        'Tenants & active leases': 'Abakodesha n’amasezerano akora',
        'Current occupants, lease terms, and direct tenant records.': 'Abakodesha ubu, igihe cy’amasezerano n’amakuru yabo.',
        'Open tenant directory': 'Fungura urutonde rw’abakodesha',
        Tenant: 'Ukodesha',
        'Property / unit': 'Inzu / icyumba',
        'Lease term': 'Igihe cy’amasezerano',
        Rent: 'Ubukode',
        Status: 'Imimerere',
        Details: 'Ibisobanuro',
        Active: 'Birakora',
        'Open unit': 'Fungura icyumba',
        'No active tenants yet. Add a lease from a unit or assign a tenant from the tenant directory.':
            'Nta bakodesha bakora. Ongeraho amasezerano ku cyumba cyangwa uhitemo ukodesha mu rutonde.',
        'Visitor inquiries': 'Ibibazo by’abasuye',
        'Contact the visitor, then mark the inquiry as read to allow a new inquiry for this property.':
            'Vugana n’uwasuye, hanyuma ushyireho ko wasomye ubutumwa kugira ngo yongere kwandikira iyi nzu.',
        New: 'Bishya',
        Call: 'Hamagara',
        'SMS visitor': 'Ohereza ubutumwa',
        Email: 'Imeyili',
        'Mark as read': 'Shyira ko wasomye',
        'No visitor inquiries yet.': 'Nta butumwa bw’abasuye burahari.',
        'Your account has expired': 'Konti yawe yarangiye',
        'Please contact support to renew access.': 'Vugana n’ubufasha kugira ngo wongere gukoresha konti.',
        'Tenant details': 'Amakuru y’ukodesha',
        'Back to tenants': 'Subira ku bakodesha',
        'Company tenant': 'Ikigo gikodesha',
        'Individual tenant': 'Umuntu ku giti cye ukodesha',
        'Close editor': 'Funga ibyo uhindura',
        'Edit tenant details': 'Hindura amakuru y’ukodesha',
        'Assign a unit': 'Shyiraho icyumba',
        'Tenant type': 'Ubwoko bw’ukodesha',
        Individual: 'Umuntu ku giti cye',
        Company: 'Ikigo',
        'First name': 'Izina',
        'Last name': 'Izina ry’umuryango',
        'Company name': 'Izina ry’ikigo',
        'Registration number': 'Nomero y’iyandikisha',
        'Company TIN': 'Nomero y’ikigo y’imisoro',
        'Representative full name': 'Amazina y’uhagarariye ikigo',
        'Save changes': 'Bika impinduka',
        Cancel: 'Kureka',
        'Create tenant': 'Ongeraho ukodesha',
        'Search tenants...': 'Shakisha abakodesha...',
        'Manage the people and businesses occupying your units.': 'Genzura abantu n’ibigo bikodesha ibyumba byawe.',
        'No tenants found': 'Nta mukodesha ubonetse',
        'Try a different search.': 'Gerageza gushakisha ukundi.',
        'Tenants will appear here when assigned to a unit.': 'Abakodesha bazagaragara aha nibamara gushyirwa mu byumba.',
        Unit: 'Icyumba',
        Payment: 'Kwishyura',
        Read: 'Byasomwe',
        'Your subscription ended on :date. Please contact support to renew access.': 'Igihe cyo gukoresha konti cyarangiye ku :date. Vugana n’ubufasha kugira ngo wongere gukoresha konti.',
        ':available available · :maintenance under maintenance': ':available birahari · :maintenance biri gusanwa',
        'Portfolio reports': 'Raporo z’imitungo',
        ':occupied occupied of :total total units': ':occupied bikodeshejwe kuri :total ibyumba byose',
    },
};
