export default {
    fr: {
        Dashboard: 'Tableau de bord',
        'Admin control center': 'Centre de contrôle administrateur',
        'Platform administration': 'Administration de la plateforme',
        'Welcome back, :name': 'Bon retour, :name',
        'Your overview of owners, approvals, subscriptions, and platform activity.': 'Vue d’ensemble des propriétaires, approbations, abonnements et activités de la plateforme.',
        'Manage accounts': 'Gérer les comptes',
        'Platform accounts': 'Comptes de la plateforme',
        ':count owner accounts': ':count comptes propriétaires',
        'Awaiting approval': 'En attente d’approbation',
        'Complete profiles ready for review': 'Profils complets prêts à être examinés',
        'Active subscriptions': 'Abonnements actifs',
        ':count expired accounts': ':count comptes expirés',
        'New owners this month': 'Nouveaux propriétaires ce mois-ci',
        'Out of :count registered owners': 'Sur :count propriétaires inscrits',
        ':count properties': ':count biens',
        ':count units': ':count unités',
        ':count new inquiries': ':count nouvelles demandes',
        'Platform overview': 'Vue d’ensemble de la plateforme',
        'Platform management': 'Gestion de la plateforme',
        'Open any area to manage records across all owners, or filter by owner.': 'Ouvrez une section pour gérer les dossiers de tous les propriétaires ou filtrer par propriétaire.',
        'Owner accounts': 'Comptes propriétaires',
        'Manage owner profiles, subscriptions, and account access.': 'Gérez les profils des propriétaires, les abonnements et les accès aux comptes.',
        'Approval queue': 'File d’approbation',
        'Review complete profiles and approve eligible owners.': 'Examinez les profils complets et approuvez les propriétaires admissibles.',
        'Properties & units': 'Biens et unités',
        'Manage properties and units across all owner portfolios.': 'Gérez les biens et les unités de tous les portefeuilles propriétaires.',
        'View and manage tenants across the platform.': 'Consultez et gérez les locataires de toute la plateforme.',
        'Lease records': 'Dossiers des baux',
        'Review lease documents and tenancy records.': 'Examinez les documents de bail et les dossiers de location.',
        'Review payment history and owner collections.': 'Examinez l’historique des paiements et les encaissements des propriétaires.',
        'Manage inquiries': 'Gérer les demandes',
        'Contact visitors by SMS, email, or phone and track inquiry status.': 'Contactez les visiteurs par SMS, e-mail ou téléphone et suivez le statut des demandes.',
        Owner: 'Propriétaire',
        'Platform reports': 'Rapports de la plateforme',
        'View financial and portfolio reports across all owners.': 'Consultez les rapports financiers et de portefeuille de tous les propriétaires.',
        'Open management': 'Ouvrir la gestion',
        'Recent owner registrations': 'Inscriptions récentes des propriétaires',
        'The latest accounts added to the platform.': 'Les derniers comptes ajoutés à la plateforme.',
        'All accounts': 'Tous les comptes',
        Joined: 'Inscrit',
        'No owner accounts yet': 'Aucun compte propriétaire pour le moment',
        'New registrations will appear here.': 'Les nouvelles inscriptions apparaîtront ici.',
        'Showing the :count most recent owner accounts': 'Affichage des :count comptes propriétaires les plus récents',
        'Needs attention': 'À traiter',
        'All caught up': 'Tout est à jour',
        'Accounts ready for approval': 'Comptes prêts à être approuvés',
        'Review completed profiles and confirm payment before activating an owner subscription.': 'Vérifiez les profils complets et confirmez le paiement avant d’activer un abonnement propriétaire.',
        'Open approval queue': 'Ouvrir la file d’approbation',
        'Admin shortcuts': 'Raccourcis administrateur',
        'Review approvals': 'Examiner les approbations',
        'Check complete owner profiles and confirm payment.': 'Vérifiez les profils propriétaires complets et confirmez le paiement.',
        'Search accounts, update plans, or export records.': 'Recherchez des comptes, modifiez les forfaits ou exportez les données.',
        'Platform properties': 'Biens de la plateforme',
        'Review properties and units across the platform.': 'Consultez les biens et les unités de toute la plateforme.',
        approved: 'approuvé',
        pending: 'en attente',
        rejected: 'refusé',
        Properties: 'Propriétés',
        Tenants: 'Locataires',
        Leases: 'Baux',
        Payments: 'Paiements',
        Messages: 'Messages',
        Reports: 'Rapports',
        Approvals: 'Approbations',
        'All Users': 'Tous les utilisateurs',
        'Admin Access': 'Accès administrateur',
        'Signed in as': 'Connecté en tant que',
        Profile: 'Profil',
        'Log Out': 'Déconnexion',
        Success: 'Succès',
        Continue: 'Continuer',
        Support: 'Assistance',
        'Help center & FAQs': "Centre d'aide et FAQ",
        'Contact admin': "Contacter l'administrateur",
        'Live chat': 'Chat en direct',
        'Privacy Policy': 'Politique de confidentialité',
        'Terms of Service': "Conditions d'utilisation",
        'Contact Us': 'Nous contacter',
        'All rights reserved. Made for landlords and tenants across Rwanda':
            'Tous droits réservés. Conçu pour les propriétaires et locataires du Rwanda',
        'EN': 'Anglais',
        'FR': 'Français',
        'RW': 'Kinyarwanda',
        'Select language': 'Choisir la langue',
        English: 'Anglais',
        Login: 'Connexion',
        Register: 'Inscription',
        'All rights reserved.': 'Tous droits réservés.',
        Phone: 'Téléphone',
        Overview: 'Vue d’ensemble',
        'Good to see you, :name': 'Heureux de vous revoir, :name',
        'Here’s what’s happening across your portfolio.': 'Voici ce qui se passe dans votre portefeuille immobilier.',
        'Add property': 'Ajouter un bien',
        'Total units': 'Nombre total d’unités',
        'Occupied units': 'Unités occupées',
        'Available units': 'Unités disponibles',
        'Portfolio occupancy': 'Occupation du portefeuille',
        occupied: 'occupées',
        'available · :count under maintenance': 'disponibles · :count en maintenance',
        'Recent properties': 'Biens récents',
        'View all': 'Tout voir',
        'No properties yet.': 'Aucun bien pour le moment.',
        'Add your first property': 'Ajoutez votre premier bien',
        'Tenants & active leases': 'Locataires et baux actifs',
        'Current occupants, lease terms, and direct tenant records.': 'Occupants actuels, conditions de bail et dossiers des locataires.',
        'Open tenant directory': 'Ouvrir le répertoire des locataires',
        Tenant: 'Locataire',
        'Property / unit': 'Bien / unité',
        'Lease term': 'Durée du bail',
        Rent: 'Loyer',
        Status: 'Statut',
        Details: 'Détails',
        Active: 'Actif',
        'Open unit': 'Ouvrir l’unité',
        'No active tenants yet. Add a lease from a unit or assign a tenant from the tenant directory.':
            'Aucun locataire actif. Ajoutez un bail depuis une unité ou attribuez un locataire depuis le répertoire.',
        'Visitor inquiries': 'Demandes des visiteurs',
        'Contact the visitor, then mark the inquiry as read to allow a new inquiry for this property.':
            'Contactez le visiteur, puis marquez la demande comme lue pour autoriser une nouvelle demande pour ce bien.',
        New: 'Nouveau',
        Call: 'Appeler',
        'SMS visitor': 'Envoyer un SMS',
        Email: 'E-mail',
        'Mark as read': 'Marquer comme lu',
        'No visitor inquiries yet.': 'Aucune demande de visiteur pour le moment.',
        'Your account has expired': 'Votre compte a expiré',
        'Please contact support to renew access.': 'Veuillez contacter l’assistance pour renouveler votre accès.',
        'Tenant details': 'Détails du locataire',
        'Back to tenants': 'Retour aux locataires',
        'Company tenant': 'Locataire entreprise',
        'Individual tenant': 'Locataire particulier',
        'Close editor': 'Fermer la modification',
        'Edit tenant details': 'Modifier les informations du locataire',
        'Assign a unit': 'Attribuer une unité',
        'Tenant type': 'Type de locataire',
        Individual: 'Particulier',
        Company: 'Entreprise',
        'First name': 'Prénom',
        'Last name': 'Nom',
        'Company name': 'Nom de l’entreprise',
        'Registration number': 'Numéro d’enregistrement',
        'Company TIN': 'Numéro d’identification fiscale de l’entreprise',
        'Representative full name': 'Nom complet du représentant',
        'Save changes': 'Enregistrer les modifications',
        'Cancel': 'Annuler',
        'Create tenant': 'Créer un locataire',
        'Search tenants...': 'Rechercher des locataires...',
        'Manage the people and businesses occupying your units.': 'Gérez les personnes et entreprises occupant vos unités.',
        'No tenants found': 'Aucun locataire trouvé',
        'Try a different search.': 'Essayez une autre recherche.',
        'Tenants will appear here when assigned to a unit.': 'Les locataires apparaîtront ici lorsqu’ils seront attribués à une unité.',
        Unit: 'Unité',
        Payment: 'Paiement',
        'Your subscription ended on :date. Please contact support to renew access.': 'Votre abonnement a pris fin le :date. Veuillez contacter l’assistance pour renouveler votre accès.',
        Read: 'Lu',
        ':available available · :maintenance under maintenance': ':available disponibles · :maintenance en maintenance',
        'Portfolio reports': 'Rapports du portefeuille',
        ':occupied occupied of :total total units': ':occupied occupées sur :total unités au total',
    },
    rw: {
        Dashboard: 'Imbonerahamwe',
        'Admin control center': 'Ikigo cy’ubuyobozi',
        'Platform administration': 'Imicungire y’urubuga',
        'Welcome back, :name': 'Murakaza neza, :name',
        'Your overview of owners, approvals, subscriptions, and platform activity.': 'Incamake y’abafite konti, ibyemezo, kwiyandikisha n’ibikorwa byo ku rubuga.',
        'Manage accounts': 'Genzura konti',
        'Platform accounts': 'Konti zo ku rubuga',
        ':count owner accounts': 'Konti :count z’abafite imitungo',
        'Awaiting approval': 'Bitegereje kwemezwa',
        'Complete profiles ready for review': 'Imyirondoro yuzuye itegereje gusuzumwa',
        'Active subscriptions': 'Konti zikora',
        ':count expired accounts': 'Konti :count zarangiye',
        'New owners this month': 'Abafite konti bashya muri uku kwezi',
        'Out of :count registered owners': 'Mu bafite konti :count biyandikishije',
        ':count properties': 'Inzu :count',
        ':count units': 'Ibyumba :count',
        ':count new inquiries': 'Ubutumwa bushya :count',
        'Platform overview': 'Incamake y’urubuga',
        'Platform management': 'Imicungire y’urubuga',
        'Open any area to manage records across all owners, or filter by owner.': 'Fungura igice ushaka gucungamo amakuru y’abafite konti bose cyangwa ushungure ukurikije nyirayo.',
        'Owner accounts': 'Konti z’abafite imitungo',
        'Manage owner profiles, subscriptions, and account access.': 'Genzura imyirondoro, konti n’uburenganzira bw’abafite imitungo.',
        'Approval queue': 'Urutonde rw’ibitegereje kwemezwa',
        'Review complete profiles and approve eligible owners.': 'Suzuma imyirondoro yuzuye wemeze abafite ibisabwa.',
        'Properties & units': 'Inzu n’ibyumba',
        'Manage properties and units across all owner portfolios.': 'Genzura inzu n’ibyumba byose by’abafite imitungo.',
        'View and manage tenants across the platform.': 'Reba kandi ucunge abakodesha bose bo ku rubuga.',
        'Lease records': 'Amasezerano y’ubukode',
        'Review lease documents and tenancy records.': 'Suzuma inyandiko z’amasezerano n’amakuru y’ubukode.',
        'Review payment history and owner collections.': 'Suzuma amateka y’ubwishyu n’amafaranga yakiriwe n’abafite imitungo.',
        'Manage inquiries': 'Genzura ubutumwa',
        'Contact visitors by SMS, email, or phone and track inquiry status.': 'Vugana n’abasuye ukoresheje SMS, imeyili cyangwa telefoni, ukurikirane uko ubutumwa buhagaze.',
        Owner: 'Nyir’umutungo',
        'Platform reports': 'Raporo zo ku rubuga',
        'View financial and portfolio reports across all owners.': 'Reba raporo z’imari n’iz’imitungo ku bafite konti bose.',
        'Open management': 'Fungura imicungire',
        'Recent owner registrations': 'Abafite konti baherutse kwiyandikisha',
        'The latest accounts added to the platform.': 'Konti ziheruka kongerwa ku rubuga.',
        'All accounts': 'Konti zose',
        Joined: 'Yiyandikishije',
        'No owner accounts yet': 'Nta konti z’abafite imitungo zirahari',
        'New registrations will appear here.': 'Abiyandikisha bashya bazagaragara hano.',
        'Showing the :count most recent owner accounts': 'Hagaragajwe konti :count ziheruka',
        'Needs attention': 'Bisaba kwitabwaho',
        'All caught up': 'Byose biragenda neza',
        'Accounts ready for approval': 'Konti ziteguye kwemezwa',
        'Review completed profiles and confirm payment before activating an owner subscription.': 'Suzuma imyirondoro yuzuye kandi wemeze ko bishyuye mbere yo gutangiza konti.',
        'Open approval queue': 'Fungura urutonde rw’ibitegereje kwemezwa',
        'Admin shortcuts': 'Ibyihutirwa by’ubuyobozi',
        'Review approvals': 'Suzuma ibyemezo',
        'Check complete owner profiles and confirm payment.': 'Suzuma imyirondoro yuzuye kandi wemeze ubwishyu.',
        'Search accounts, update plans, or export records.': 'Shakisha konti, hindura gahunda cyangwa wohereze amakuru hanze.',
        'Platform properties': 'Inzu zo ku rubuga',
        'Review properties and units across the platform.': 'Suzuma inzu n’ibyumba byo ku rubuga.',
        approved: 'yemejwe',
        pending: 'itegereje',
        rejected: 'yanzewe',
        Properties: 'Inzu',
        Tenants: 'Abakodesha',
        Leases: 'Amasezerano y’ubukode',
        Payments: 'Kwishyura',
        Messages: 'Ubutumwa',
        Reports: 'Raporo',
        Approvals: 'Ibyemezo',
        'All Users': 'Abakoresha bose',
        'Admin Access': 'Ubuyobozi',
        'Signed in as': 'Winjiye nka',
        Profile: 'Umwirondoro',
        'Log Out': 'Sohoka',
        Success: 'Byagenze neza',
        Continue: 'Komeza',
        Support: 'Ubufasha',
        'Help center & FAQs': 'Ubufasha n’ibisubizo ku bibazo',
        'Contact admin': 'Vugana n’ubuyobozi',
        'Live chat': 'Ubutumwa ako kanya',
        'Privacy Policy': 'Amabwiriza y’ibanga',
        'Terms of Service': 'Amabwiriza y’imikoreshereze',
        'Contact Us': 'Twandikire',
        'All rights reserved. Made for landlords and tenants across Rwanda':
            'Uburenganzira bwose burabitswe. Byagenewe abakodesha n’abakodeshwa mu Rwanda',
        EN: 'Icyongereza',
        FR: 'Igifaransa',
        RW: 'Ikinyarwanda',
        'Select language': 'Hitamo ururimi',
        English: 'Icyongereza',
        Login: 'Injira',
        Register: 'Iyandikishe',
        'All rights reserved.': 'Uburenganzira bwose burabitswe.',
        Phone: 'Telefoni',
        Overview: 'Incamake',
        'Good to see you, :name': 'Neza kukubona, :name',
        'Here’s what’s happening across your portfolio.': 'Dore ibiri kubera mu mitungo yawe.',
        'Add property': 'Ongeraho inzu',
        'Total units': 'Ibyumba byose',
        'Occupied units': 'Ibyumba bikodeshejwe',
        'Available units': 'Ibyumba bihari',
        'Portfolio occupancy': 'Imikoreshereze y’imitungo',
        occupied: 'birakodeshejwe',
        'available · :count under maintenance': 'birahari · :count biri gusanwa',
        'Recent properties': 'Inzu ziheruka',
        'View all': 'Reba byose',
        'No properties yet.': 'Nta nzu zirahari.',
        'Add your first property': 'Ongeraho inzu ya mbere',
        'Tenants & active leases': 'Abakodesha n’amasezerano akora',
        'Current occupants, lease terms, and direct tenant records.': 'Abakodesha ubu, igihe cy’amasezerano n’amakuru yabo.',
        'Open tenant directory': 'Fungura urutonde rw’abakodesha',
        Tenant: 'Ukodesha',
        'Property / unit': 'Inzu / icyumba',
        'Lease term': 'Igihe cy’amasezerano',
        Rent: 'Ubukode',
        Status: 'Imimerere',
        Details: 'Ibisobanuro',
        Active: 'Birakora',
        'Open unit': 'Fungura icyumba',
        'No active tenants yet. Add a lease from a unit or assign a tenant from the tenant directory.':
            'Nta bakodesha bakora. Ongeraho amasezerano ku cyumba cyangwa uhitemo ukodesha mu rutonde.',
        'Visitor inquiries': 'Ibibazo by’abasuye',
        'Contact the visitor, then mark the inquiry as read to allow a new inquiry for this property.':
            'Vugana n’uwasuye, hanyuma ushyireho ko wasomye ubutumwa kugira ngo yongere kwandikira iyi nzu.',
        New: 'Bishya',
        Call: 'Hamagara',
        'SMS visitor': 'Ohereza ubutumwa',
        Email: 'Imeyili',
        'Mark as read': 'Shyira ko wasomye',
        'No visitor inquiries yet.': 'Nta butumwa bw’abasuye burahari.',
        'Your account has expired': 'Konti yawe yarangiye',
        'Please contact support to renew access.': 'Vugana n’ubufasha kugira ngo wongere gukoresha konti.',
        'Tenant details': 'Amakuru y’ukodesha',
        'Back to tenants': 'Subira ku bakodesha',
        'Company tenant': 'Ikigo gikodesha',
        'Individual tenant': 'Umuntu ku giti cye ukodesha',
        'Close editor': 'Funga ibyo uhindura',
        'Edit tenant details': 'Hindura amakuru y’ukodesha',
        'Assign a unit': 'Shyiraho icyumba',
        'Tenant type': 'Ubwoko bw’ukodesha',
        Individual: 'Umuntu ku giti cye',
        Company: 'Ikigo',
        'First name': 'Izina',
        'Last name': 'Izina ry’umuryango',
        'Company name': 'Izina ry’ikigo',
        'Registration number': 'Nomero y’iyandikisha',
        'Company TIN': 'Nomero y’ikigo y’imisoro',
        'Representative full name': 'Amazina y’uhagarariye ikigo',
        'Save changes': 'Bika impinduka',
        Cancel: 'Kureka',
        'Create tenant': 'Ongeraho ukodesha',
        'Search tenants...': 'Shakisha abakodesha...',
        'Manage the people and businesses occupying your units.': 'Genzura abantu n’ibigo bikodesha ibyumba byawe.',
        'No tenants found': 'Nta mukodesha ubonetse',
        'Try a different search.': 'Gerageza gushakisha ukundi.',
        'Tenants will appear here when assigned to a unit.': 'Abakodesha bazagaragara aha nibamara gushyirwa mu byumba.',
        Unit: 'Icyumba',
        Payment: 'Kwishyura',
        Read: 'Byasomwe',
        'Your subscription ended on :date. Please contact support to renew access.': 'Igihe cyo gukoresha konti cyarangiye ku :date. Vugana n’ubufasha kugira ngo wongere gukoresha konti.',
        ':available available · :maintenance under maintenance': ':available birahari · :maintenance biri gusanwa',
        'Portfolio reports': 'Raporo z’imitungo',
        ':occupied occupied of :total total units': ':occupied bikodeshejwe kuri :total ibyumba byose',
    },
};
