export default {
    fr: {
        'Lease documents': 'Documents de bail',
        'Signed agreements and renewals attached to your tenancies.': 'Contrats signés et renouvellements associés à vos locations.',
        Tenant: 'Locataire',
        'Property / unit': 'Bien / unité',
        'Lease term': 'Durée du bail',
        'Payments due to date': 'Paiements dus à ce jour',
        Uploaded: 'Téléversé le',
        Ongoing: 'En cours',
        Unknown: 'Inconnu',
        Download: 'Télécharger',
        Unavailable: 'Indisponible',
        'Manage tenancy': 'Gérer la location',
        'No lease documents yet': 'Aucun document de bail',
        'Upload signed agreements from a unit’s tenancy section.': 'Téléversez les contrats signés depuis la section location de l’unité.',
        'Browse properties': 'Parcourir les biens',
        'outstanding': 'impayé',
        'Rent & deposit payments': 'Paiements du loyer et du dépôt',
        'Track charges, record partial or full payments, and issue receipts.': 'Suivez les frais, enregistrez les paiements partiels ou complets et émettez des reçus.',
        'All charges': 'Tous les frais',
        Outstanding: 'Impayés',
        Overdue: 'En retard',
        Paid: 'Payé',
        Cancelled: 'Annulé',
        Remaining: 'Restant',
        'Paid in full': 'Entièrement payé',
        'Amount (max :amount RWF)': 'Montant (maximum :amount RWF)',
        'Payment method': 'Mode de paiement',
        Cash: 'Espèces',
        'Bank transfer': 'Virement bancaire',
        'Mobile money': 'Mobile Money',
        Other: 'Autre',
        'Received at': 'Reçu le',
        'Reference (optional)': 'Référence (facultatif)',
        'Payment note (optional)': 'Note de paiement (facultatif)',
        'Saving payment…': 'Enregistrement du paiement…',
        'Record payment': 'Enregistrer le paiement',
        'No charges found': 'Aucun frais trouvé',
        'Rent and deposit charges are created from the tenancy schedule.': 'Les frais de loyer et de dépôt sont créés selon le calendrier de location.',
        'View properties': 'Voir les biens',
        'Portfolio reports': 'Rapports du portefeuille',
        'A current overview of occupancy, leases, charges, and money received.': 'Vue actuelle de l’occupation, des baux, des frais et des paiements reçus.',
        'Occupancy rate': 'Taux d’occupation',
        'Active leases': 'Baux actifs',
        'Expiring in 30 days': 'Expirant dans 30 jours',
        'Collected this month': 'Montant encaissé ce mois',
        'Outstanding balance': 'Solde impayé',
        'Overdue balance': 'Solde en retard',
        'Property occupancy': 'Occupation des biens',
        'Manage properties': 'Gérer les biens',
        Units: 'Unités',
        Occupancy: 'Occupation',
        Available: 'Disponibles',
        'Current tenants': 'Locataires actuels',
        'No active tenants': 'Aucun locataire actif',
        'Add a property to start seeing portfolio reports.': 'Ajoutez un bien pour commencer à voir les rapports du portefeuille.',
        'Review lease documents': 'Consulter les documents de bail',
        'Review payments': 'Consulter les paiements',
        'Create tenant': 'Créer un locataire',
        'Identity and contact details are required for all tenants.': 'Les informations d’identité et de contact sont requises pour tous les locataires.',
        Identity: 'Identité',
        Contact: 'Contact',
        'Active units': 'Unités actives',
        Property: 'Bien',
        Action: 'Action',
        Passport: 'Passeport',
        ID: 'Pièce d’identité',
        Representative: 'Représentant',
        'No email': 'Aucun e-mail',
        'View & assign': 'Voir et attribuer',
        'No :status charges found': 'Aucun frais :status trouvé',
        Payment: 'Paiement',
        Unit: 'Unité',
        'Due': 'À payer',
        'Up to date': 'À jour',
        'Partially paid': 'Partiellement payé',
        'Expiring soon': 'Expire bientôt',
        Scheduled: 'Programmé',
        Ended: 'Terminé',
        Expired: 'Expiré',
        rent: 'loyer',
        deposit: 'dépôt',
        ':occupied occupied of :total total units': ':occupied occupées sur :total unités au total',
        'Assign this tenant to a unit': 'Attribuer ce locataire à une unité',
        'Choose an available unit, confirm the lease terms, and upload the signed lease. The unit will be reserved for a future start date.': 'Choisissez une unité disponible, confirmez les conditions du bail et téléversez le bail signé. L’unité sera réservée pour une date de début ultérieure.',
        'Available unit': 'Unité disponible',
        'Select a property and unit': 'Sélectionnez un bien et une unité',
        'Lease start date': 'Date de début du bail',
        'Lease end date': 'Date de fin du bail',
        'Rent frequency': 'Fréquence du loyer',
        Daily: 'Quotidien',
        Weekly: 'Hebdomadaire',
        Monthly: 'Mensuel',
        Quarterly: 'Trimestriel',
        Yearly: 'Annuel',
        'Rent per period (RWF)': 'Loyer par période (RWF)',
        'Monthly due day': 'Jour d’échéance mensuel',
        'Security deposit (RWF)': 'Dépôt de garantie (RWF)',
        'Signed lease document (required)': 'Document de bail signé (obligatoire)',
        'Notes (optional)': 'Notes (facultatif)',
        'Tenant identity and contact details will be reused from this profile.': 'Les informations d’identité et de contact du locataire seront reprises de ce profil.',
        'Saving tenancy…': 'Enregistrement de la location…',
        'Assign unit and create lease': 'Attribuer l’unité et créer le bail',
        'No available units right now': 'Aucune unité disponible pour le moment',
        'Create or make a unit available, then return here to assign it to :name.': 'Créez ou libérez une unité, puis revenez ici pour l’attribuer à :name.',
        'Full name': 'Nom complet',
        'Company registration number': 'Numéro d’enregistrement de l’entreprise',
        'Identity type': 'Type de pièce d’identité',
        'Identity number': 'Numéro d’identité',
        'National ID': 'Carte d’identité nationale',
        'Passport number': 'Numéro de passeport',
        'Save tenant details': 'Enregistrer les informations du locataire',
        'No unit has been assigned to this tenant yet. Use the assignment form above to get started.': 'Aucune unité n’a encore été attribuée à ce locataire. Utilisez le formulaire ci-dessus pour commencer.',
        Collected: 'Encaissé',
        'Open unit': 'Ouvrir l’unité',
        'Add Unit to :property': 'Ajouter une unité à :property',
        'Add Unit': 'Ajouter une unité',
        'Back to Units': 'Retour aux unités',
        'Unit Information': 'Informations sur l’unité',
        'Unit Number': 'Numéro de l’unité',
        'e.g., A-101, B-205': 'ex. : A-101, B-205',
        'Unit Type': 'Type d’unité',
        'Select Unit Type': 'Sélectionnez un type d’unité',
        '0 for ground floor, 1 for first floor': '0 pour le rez-de-chaussée, 1 pour le premier étage',
        'Monthly Rent (RWF)': 'Loyer mensuel (RWF)',
        'e.g., 150000': 'ex. : 150000',
        'Rent Frequency': 'Fréquence du loyer',
        'Unit Size (m²)': 'Surface de l’unité (m²)',
        'e.g., 60': 'ex. : 60',
        'Describe the unit features, amenities, etc.': 'Décrivez les caractéristiques et équipements de l’unité.',
        Maintenance: 'Maintenance',
        Reserved: 'Réservée',
        Inactive: 'Inactive',
        'Unit Images': 'Images de l’unité',
        'Add up to 10 JPG, PNG, GIF, or WebP images. Maximum 2 MB each.': 'Ajoutez jusqu’à 10 images JPG, PNG, GIF ou WebP. 2 Mo maximum chacune.',
        'Select images': 'Sélectionner des images',
        'Creating...': 'Création...',
        'Create Unit': 'Créer l’unité',
        'Edit Unit - :number': 'Modifier l’unité - :number',
        'Updating...': 'Mise à jour...',
        'Update Unit': 'Mettre à jour l’unité',
        'Cover image': 'Image de couverture',
        'Unit image': 'Image de l’unité',
        'Remove unit image': 'Supprimer l’image de l’unité',
        'Search properties...': 'Rechercher des biens...',
        'Add Property': 'Ajouter un bien',
        'No properties found': 'Aucun bien trouvé',
        'Try adjusting your search filters': 'Essayez de modifier vos filtres de recherche',
        'Get started by adding your first property': 'Commencez par ajouter votre premier bien',
        Occupied: 'Occupé',
        Maint: 'Maintenance',
        'Created by:': 'Créé par :',
        'Reg.': 'Enr.',
        Parking: 'Stationnement',
        Security: 'Sécurité',
        Gym: 'Salle de sport',
        Pool: 'Piscine',
        Restaurant: 'Restaurant',
        Bar: 'Bar',
        unit: 'unité',
        units: 'unités',
        ':count :unit': ':count :unit',
        View: 'Voir',
        'Showing :from to :to of :total properties': 'Affichage de :from à :to sur :total biens',
        'Delete Property': 'Supprimer le bien',
        'Are you sure you want to delete :name? This action cannot be undone and will also delete all associated units and images.': 'Voulez-vous vraiment supprimer :name ? Cette action est irréversible et supprimera également toutes les unités et images associées.',
        Delete: 'Supprimer',
        'Unit and tenancy history': 'Historique des unités et locations',
        'Current, upcoming, and previous leases for this tenant.': 'Baux actuels, à venir et précédents de ce locataire.',
        'Move-out deposit': 'Dépôt de garantie au départ',
        refunded: 'remboursé',
        deducted: 'déduit',
        ':property - Units': ':property - unités',
        Actions: 'Actions',
        'All Status': 'Tous les statuts',
        'Assign tenant': 'Attribuer un locataire',
        'Back to Property': 'Retour au bien',
        'New Tenant': 'Nouveau locataire',
        'No units found': 'Aucune unité trouvée',
        'Search units...': 'Rechercher des unités...',
        Size: 'Surface',
        ':type charge': 'Frais :type',
        ':unit - Details': ':unit - détails',
        'A renewal is scheduled to start on :date; it will activate automatically on that date.': 'Un renouvellement est prévu le :date ; il sera activé automatiquement à cette date.',
        Cell: 'Cellule',
        District: 'District',
        'Due / overdue balance': 'Solde dû / en retard',
        'Edit Unit': 'Modifier l’unité',
        'Edit this Unit': 'Modifier cette unité',
        'Go to Property': 'Aller au bien',
        'Ledger charges': 'Frais du registre',
        Method: 'Mode',
        'Monthly Rent': 'Loyer mensuel',
        'No leases uploaded yet.': 'Aucun bail téléversé pour le moment.',
        'No rent charges yet. Scheduled charge generation will fill missing periods automatically.': 'Aucun frais de loyer pour le moment. La génération planifiée ajoutera automatiquement les périodes manquantes.',
        'Optional note': 'Note facultative',
        'PDF, DOC, DOCX, JPG, JPEG or PNG. Maximum 10 MB.': 'PDF, DOC, DOCX, JPG, JPEG ou PNG. 10 Mo maximum.',
        'Paid at': 'Payé le',
        'Payment amount': 'Montant du paiement',
        'Property Location': 'Emplacement du bien',
        Province: 'Province',
        'Quick Actions': 'Actions rapides',
        'Renew lease': 'Renouveler le bail',
        'Rent and deposit ledger': 'Registre des loyers et dépôts',
        'Rent per period': 'Loyer par période',
        'Size (m²)': 'Surface (m²)',
        Starts: 'Commence le',
        'Tenancy & lease': 'Location et bail',
        'The next term is linked to this tenancy. Its deposit carries forward without being charged again.': 'La prochaine période est liée à cette location. Le dépôt est reporté sans être facturé à nouveau.',
        'The unit is reserved and will become occupied automatically on the start date.': 'L’unité est réservée et sera automatiquement occupée à la date de début.',
        'Unit :unit': 'Unité :unit',
        'Unit Details': 'Détails de l’unité',
        'Upcoming move-in scheduled': 'Emménagement à venir programmé',
        'Upload another signed lease or amendment': 'Téléverser un autre bail signé ou un avenant',
        'Upload lease': 'Téléverser le bail',
        'Uploading…': 'Téléversement…',
        'View All Units': 'Voir toutes les unités',
        to: 'au',
        'Are you sure you want to delete unit :unit? This action cannot be undone.': 'Voulez-vous vraiment supprimer l’unité :unit ? Cette action est irréversible.',
        'Create tenancy': 'Créer la location',
        'Create tenancy for :unit': 'Créer une location pour :unit',
        'Delete Unit': 'Supprimer l’unité',
        Notes: 'Notes',
        'Residential / business address': 'Adresse résidentielle / professionnelle',
        'Showing :from to :to of :total units': 'Affichage de :from à :to sur :total unités',
        'Signed lease (PDF, DOC, DOCX, JPG or PNG)': 'Bail signé (PDF, DOC, DOCX, JPG ou PNG)',
        'Tenancy end date': 'Date de fin de location',
        'Tenancy start date': 'Date de début de location',
        'Tenant identity, contact information, signed lease, and rent terms are required.': 'L’identité du locataire, ses coordonnées, le bail signé et les conditions de loyer sont requis.',
        'The first full rent period starts on the tenancy start date.': 'La première période complète de loyer commence à la date de début de location.',
        'Condition / inspection notes': 'Notes sur l’état / l’inspection',
        'Deduction explanation': 'Justification des retenues',
        'Deductions (RWF)': 'Déductions (RWF)',
        'Deposit received': 'Dépôt reçu',
        'Due day': 'Jour d’échéance',
        'Move-out date': 'Date de départ',
        'Move-out inspection': 'Inspection de départ',
        'Needs maintenance': 'Nécessite un entretien',
        'New lease end': 'Fin du nouveau bail',
        'New lease start': 'Début du nouveau bail',
        'Record the unit condition and reconcile all received deposits before closing the tenancy.': 'Consignez l’état de l’unité et rapprochez tous les dépôts reçus avant de clôturer la location.',
        'Refund (RWF)': 'Remboursement (RWF)',
        'Save renewal': 'Enregistrer le renouvellement',
        'Signed renewal lease': 'Bail de renouvellement signé',
        'Unit after move-out': 'État de l’unité après le départ',
        Deposit: 'Dépôt',
        'Previous agreements remain available for audit and financial history.': 'Les contrats précédents restent disponibles pour le suivi et l’historique financier.',
        'Rent/deposit payments recorded': 'Paiements de loyer/dépôt enregistrés',
        'Tenancy history': 'Historique de location',
        received: 'reçu',
        available: 'disponible',
        occupied: 'occupé',
        maintenance: 'maintenance',
        reserved: 'réservé',
        inactive: 'inactif',
        active: 'actif',
        scheduled: 'programmé',
        ended: 'terminé',
        cancelled: 'annulé',
    },
    rw: {
        'Lease documents': 'Inyandiko z’amasezerano',
        'Signed agreements and renewals attached to your tenancies.': 'Amasezerano yasinywe n’ayongereweho ajyanye n’ubukode bwawe.',
        Tenant: 'Ukodesha',
        'Property / unit': 'Inzu / icyumba',
        'Lease term': 'Igihe cy’amasezerano',
        'Payments due to date': 'Amafaranga agomba kwishyurwa kugeza ubu',
        Uploaded: 'Byashyizweho',
        Ongoing: 'Birakomeza',
        Unknown: 'Ntibizwi',
        Download: 'Manura',
        Unavailable: 'Ntibiboneka',
        'Manage tenancy': 'Genzura ubukode',
        'No lease documents yet': 'Nta nyandiko z’amasezerano zirahari',
        'Upload signed agreements from a unit’s tenancy section.': 'Shyira amasezerano yasinywe mu gice cy’ubukode bw’icyumba.',
        'Browse properties': 'Reba inzu',
        'outstanding': 'asigaye kwishyurwa',
        'Rent & deposit payments': 'Ubukode n’amafaranga y’ingwate',
        'Track charges, record partial or full payments, and issue receipts.': 'Kurikirana amafaranga agomba kwishyurwa, andika ayishyuwe yose cyangwa igice, utange inyemezabwishyu.',
        'All charges': 'Amafaranga yose',
        Outstanding: 'Asigaye',
        Overdue: 'Yarengeje igihe',
        Paid: 'Yishyuwe',
        Cancelled: 'Byahagaritswe',
        Remaining: 'Asigaye',
        'Paid in full': 'Yishyuwe yose',
        'Amount (max :amount RWF)': 'Amafaranga (ntarengwa :amount RWF)',
        'Payment method': 'Uburyo bwo kwishyura',
        Cash: 'Amafaranga mu ntoki',
        'Bank transfer': 'Kohereza kuri banki',
        'Mobile money': 'Mobile Money',
        Other: 'Ubundi',
        'Received at': 'Yakiriwe ku',
        'Reference (optional)': 'Inomero ibaranga (si ngombwa)',
        'Payment note (optional)': 'Ibisobanuro ku kwishyura (si ngombwa)',
        'Saving payment…': 'Birabikwa...',
        'Record payment': 'Andika ko yishyuwe',
        'No charges found': 'Nta mafaranga aboneka',
        'Rent and deposit charges are created from the tenancy schedule.': 'Amafaranga y’ubukode n’ingwate ategurwa hakurikijwe gahunda y’ubukode.',
        'View properties': 'Reba inzu',
        'Portfolio reports': 'Raporo z’imitungo',
        'A current overview of occupancy, leases, charges, and money received.': 'Incamake y’ubu y’ibyumba bikodeshejwe, amasezerano, amafaranga agomba kwishyurwa n’ayakiriwe.',
        'Occupancy rate': 'Igipimo cy’ibyumba bikodeshejwe',
        'Active leases': 'Amasezerano akora',
        'Expiring in 30 days': 'Azarangira mu minsi 30',
        'Collected this month': 'Amafaranga yakiriwe muri uku kwezi',
        'Outstanding balance': 'Amafaranga asigaye kwishyurwa',
        'Overdue balance': 'Amafaranga yarengeje igihe',
        'Property occupancy': 'Imikoreshereze y’inzu',
        'Manage properties': 'Genzura inzu',
        Units: 'Ibyumba',
        Occupancy: 'Ibyumba bikodeshejwe',
        Available: 'Birahari',
        'Current tenants': 'Abakodesha ubu',
        'No active tenants': 'Nta bakodesha bakora',
        'Add a property to start seeing portfolio reports.': 'Ongeraho inzu kugira ngo utangire kubona raporo z’imitungo.',
        'Review lease documents': 'Reba inyandiko z’amasezerano',
        'Review payments': 'Reba ibyishyuwe',
        'Create tenant': 'Ongeraho ukodesha',
        'Identity and contact details are required for all tenants.': 'Amakuru y’irangamuntu n’itumanaho arakenewe ku bakodesha bose.',
        Identity: 'Irangamuntu',
        Contact: 'Itumanaho',
        'Active units': 'Ibyumba bikora',
        Property: 'Inzu',
        Action: 'Igikorwa',
        Passport: 'Pasiporo',
        ID: 'Indangamuntu',
        Representative: 'Uhagarariye ikigo',
        'No email': 'Nta imeyili',
        'View & assign': 'Reba unashyireho',
        'No :status charges found': 'Nta mafaranga :status aboneka',
        Payment: 'Kwishyura',
        Unit: 'Icyumba',
        Due: 'Agomba kwishyurwa',
        'Up to date': 'Kugeza ubu nta yandi abereyemo',
        'Partially paid': 'Yishyuwe igice',
        'Expiring soon': 'Agiye kurangira vuba',
        Scheduled: 'Byateganyijwe',
        Ended: 'Byarangiye',
        Expired: 'Byarengeje igihe',
        rent: 'ubukode',
        deposit: 'ingwate',
        ':occupied occupied of :total total units': ':occupied bikodeshejwe kuri :total ibyumba byose',
        'Assign this tenant to a unit': 'Shyira uyu mukodesha mu cyumba',
        'Choose an available unit, confirm the lease terms, and upload the signed lease. The unit will be reserved for a future start date.': 'Hitamo icyumba gihari, wemeze ibikubiye mu masezerano, ushyireho amasezerano yasinywe. Icyumba kizabikirwa itariki yo gutangira izaza.',
        'Available unit': 'Icyumba gihari',
        'Select a property and unit': 'Hitamo inzu n’icyumba',
        'Lease start date': 'Itariki amasezerano atangirira',
        'Lease end date': 'Itariki amasezerano arangirira',
        'Rent frequency': 'Inshuro z’ubukode',
        Daily: 'Buri munsi',
        Weekly: 'Buri cyumweru',
        Monthly: 'Buri kwezi',
        Quarterly: 'Buri mezi atatu',
        Yearly: 'Buri mwaka',
        'Rent per period (RWF)': 'Ubukode kuri buri gihe (RWF)',
        'Monthly due day': 'Umunsi wo kwishyura buri kwezi',
        'Security deposit (RWF)': 'Amafaranga y’ingwate (RWF)',
        'Signed lease document (required)': 'Inyandiko y’amasezerano yasinywe (irakenewe)',
        'Notes (optional)': 'Ibisobanuro (si ngombwa)',
        'Tenant identity and contact details will be reused from this profile.': 'Amakuru y’irangamuntu n’itumanaho by’ukodesha bizava muri iyi konti.',
        'Saving tenancy…': 'Turimo kubika ubukode...',
        'Assign unit and create lease': 'Shyira mu cyumba unakore amasezerano',
        'No available units right now': 'Nta byumba bihari ubu',
        'Create or make a unit available, then return here to assign it to :name.': 'Kora icyumba cyangwa ugishyire ku isoko, hanyuma ugaruke kugishyira kuri :name.',
        'Full name': 'Amazina yose',
        'Company registration number': 'Nomero y’iyandikisha ry’ikigo',
        'Identity type': 'Ubwoko bw’indangamuntu',
        'Identity number': 'Nomero y’indangamuntu',
        'National ID': 'Indangamuntu',
        'Passport number': 'Nomero ya pasiporo',
        'Save tenant details': 'Bika amakuru y’ukodesha',
        'No unit has been assigned to this tenant yet. Use the assignment form above to get started.': 'Nta cyumba kirashyirwa kuri uyu mukodesha. Koresha ifomu iri hejuru utangire.',
        Collected: 'Yishyuwe',
        'Open unit': 'Fungura icyumba',
        'Add Unit to :property': 'Ongeraho icyumba muri :property',
        'Add Unit': 'Ongeraho icyumba',
        'Back to Units': 'Subira ku byumba',
        'Unit Information': 'Amakuru y’icyumba',
        'Unit Number': 'Nomero y’icyumba',
        'e.g., A-101, B-205': 'urugero: A-101, B-205',
        'Unit Type': 'Ubwoko bw’icyumba',
        'Select Unit Type': 'Hitamo ubwoko bw’icyumba',
        '0 for ground floor, 1 for first floor': '0 ku igorofa ryo hasi, 1 ku rya mbere',
        'Monthly Rent (RWF)': 'Ubukode bw’ukwezi (RWF)',
        'e.g., 150000': 'urugero: 150000',
        'Rent Frequency': 'Inshuro z’ubukode',
        'Unit Size (m²)': 'Ingano y’icyumba (m²)',
        'e.g., 60': 'urugero: 60',
        'Describe the unit features, amenities, etc.': 'Sobanura ibiranga icyumba n’ibikoresho kirimo.',
        Maintenance: 'Birimo gusanwa',
        Reserved: 'Byabitswe',
        Inactive: 'Ntibikora',
        'Unit Images': 'Amafoto y’icyumba',
        'Add up to 10 JPG, PNG, GIF, or WebP images. Maximum 2 MB each.': 'Ongeraho amafoto agera ku 10 ya JPG, PNG, GIF cyangwa WebP. Ntarengwa ni 2 MB kuri buri foto.',
        'Select images': 'Hitamo amafoto',
        'Creating...': 'Turimo gukora...',
        'Create Unit': 'Kora icyumba',
        'Edit Unit - :number': 'Hindura icyumba - :number',
        'Updating...': 'Turimo kuvugurura...',
        'Update Unit': 'Vugurura icyumba',
        'Cover image': 'Ifoto y’ingenzi',
        'Unit image': 'Ifoto y’icyumba',
        'Remove unit image': 'Siba ifoto y’icyumba',
        'Search properties...': 'Shakisha inzu...',
        'Add Property': 'Ongeraho inzu',
        'No properties found': 'Nta nzu yabonetse',
        'Try adjusting your search filters': 'Gerageza guhindura ibyo washakishije',
        'Get started by adding your first property': 'Tangira wongeraho inzu ya mbere',
        Occupied: 'Kirakodeshwa',
        Maint: 'Birakorwa',
        'Created by:': 'Yakozwe na:',
        'Reg.': 'Kwiyandikisha',
        Parking: 'Aho guhagarika imodoka',
        Security: 'Umutekano',
        Gym: 'Aho gukorera imyitozo',
        Pool: 'Pisine',
        Restaurant: 'Resitora',
        Bar: 'Akabari',
        unit: 'icyumba',
        units: 'ibyumba',
        ':count :unit': ':count :unit',
        View: 'Reba',
        'Showing :from to :to of :total properties': 'Herekanwa :from kugeza :to kuri :total inzu',
        'Delete Property': 'Siba inzu',
        'Are you sure you want to delete :name? This action cannot be undone and will also delete all associated units and images.': 'Uremeza ko ushaka gusiba :name? Ntibishobora gusubirwaho kandi n’ibyumba n’amafoto biyifitanye isano birasibwa.',
        Delete: 'Siba',
        'Unit and tenancy history': 'Amateka y’ibyumba n’ubukode',
        'Current, upcoming, and previous leases for this tenant.': 'Amasezerano y’ubu, ateganyijwe n’ayabanje kuri uyu mukodesha.',
        'Move-out deposit': 'Ingwate igihe cyo kwimuka',
        refunded: 'yasubijwe',
        deducted: 'yakuwemo',
        ':property - Units': ':property - ibyumba',
        Actions: 'Ibikorwa',
        'All Status': 'Imiterere yose',
        'Assign tenant': 'Shyiraho umukodesha',
        'Back to Property': 'Subira ku nzu',
        'New Tenant': 'Umukodesha mushya',
        'No units found': 'Nta byumba byabonetse',
        'Search units...': 'Shakisha ibyumba...',
        Size: 'Ingano',
        ':type charge': 'Amafaranga ya :type',
        ':unit - Details': ':unit - ibisobanuro',
        'A renewal is scheduled to start on :date; it will activate automatically on that date.': 'Kongera amasezerano bizatangira ku wa :date kandi bizikora kuri uwo munsi.',
        Cell: 'Akagari',
        District: 'Akarere',
        'Due / overdue balance': 'Amafaranga agomba kwishyurwa cyangwa yarengeje igihe',
        'Edit Unit': 'Hindura icyumba',
        'Edit this Unit': 'Hindura iki cyumba',
        'Go to Property': 'Jya ku nzu',
        'Ledger charges': 'Amafaranga ategereje kwishyurwa',
        Method: 'Uburyo',
        'Monthly Rent': 'Ubukode bw’ukwezi',
        'No leases uploaded yet.': 'Nta masezerano yashyizweho.',
        'No rent charges yet. Scheduled charge generation will fill missing periods automatically.': 'Nta mafaranga y’ubukode arashyirwaho. Gahunda izongeraho ibihe byabuze mu buryo bwikora.',
        'Optional note': 'Icyitonderwa si ngombwa',
        'PDF, DOC, DOCX, JPG, JPEG or PNG. Maximum 10 MB.': 'PDF, DOC, DOCX, JPG, JPEG cyangwa PNG. Ntarengwa ni 10 MB.',
        'Paid at': 'Yishyuwe ku',
        'Payment amount': 'Amafaranga yishyuwe',
        'Property Location': 'Aho inzu iherereye',
        Province: 'Intara',
        'Quick Actions': 'Ibikorwa byihuse',
        'Renew lease': 'Ongera amasezerano',
        'Rent and deposit ledger': 'Ibaruramari ry’ubukode n’ingwate',
        'Rent per period': 'Ubukode kuri buri gihe',
        'Size (m²)': 'Ingano (m²)',
        Starts: 'Bitangira',
        'Tenancy & lease': 'Ubukode n’amasezerano',
        'The next term is linked to this tenancy. Its deposit carries forward without being charged again.': 'Igihe gikurikira gihuzwa n’ubu bukode. Ingwate irakomeza ntisubire kubarwa.',
        'The unit is reserved and will become occupied automatically on the start date.': 'Icyumba cyarabitswe kandi kizahita gikoreshwa ku itariki yo gutangira.',
        'Unit :unit': 'Icyumba :unit',
        'Unit Details': 'Ibisobanuro by’icyumba',
        'Upcoming move-in scheduled': 'Kwimukiramo guteganyijwe',
        'Upload another signed lease or amendment': 'Shyiraho andi masezerano yasinywe cyangwa inyongera yayo',
        'Upload lease': 'Shyiraho amasezerano',
        'Uploading…': 'Birashyirwaho…',
        'View All Units': 'Reba ibyumba byose',
        to: 'kugeza',
        'Are you sure you want to delete unit :unit? This action cannot be undone.': 'Uremeza ko ushaka gusiba icyumba :unit? Iki gikorwa ntigishobora gusubirwaho.',
        'Create tenancy': 'Kora ubukode',
        'Create tenancy for :unit': 'Kora ubukode bw’icyumba :unit',
        'Delete Unit': 'Siba icyumba',
        Notes: 'Ibisobanuro',
        'Residential / business address': 'Aderesi yo guturamo / y’akazi',
        'Showing :from to :to of :total units': 'Herekanwa :from kugeza :to kuri :total byumba',
        'Signed lease (PDF, DOC, DOCX, JPG or PNG)': 'Amasezerano yasinywe (PDF, DOC, DOCX, JPG cyangwa PNG)',
        'Tenancy end date': 'Itariki ubukode burangirira',
        'Tenancy start date': 'Itariki ubukode butangirira',
        'Tenant identity, contact information, signed lease, and rent terms are required.': 'Birakenewe umwirondoro n’aho umukodesha abarizwa, amasezerano yasinywe n’amabwiriza y’ubukode.',
        'The first full rent period starts on the tenancy start date.': 'Igihe cya mbere cyuzuye cy’ubukode gitangira ku itariki ubukode butangiriyeho.',
        'Condition / inspection notes': 'Ibisobanuro ku mimerere / igenzura',
        'Deduction explanation': 'Impamvu y’amafaranga yakuweho',
        'Deductions (RWF)': 'Amafaranga yakuweho (RWF)',
        'Deposit received': 'Ingwate yakiriwe',
        'Due day': 'Umunsi wo kwishyura',
        'Move-out date': 'Itariki yo kwimuka',
        'Move-out inspection': 'Igenzura igihe cyo kwimuka',
        'Needs maintenance': 'Ikeneye gusanwa',
        'New lease end': 'Iherezo ry’amasezerano mashya',
        'New lease start': 'Intangiriro y’amasezerano mashya',
        'Record the unit condition and reconcile all received deposits before closing the tenancy.': 'Andika uko icyumba kimeze kandi ugenzure ingwate zose zakiriwe mbere yo gusoza ubukode.',
        'Refund (RWF)': 'Amafaranga asubizwa (RWF)',
        'Save renewal': 'Bika kongera amasezerano',
        'Signed renewal lease': 'Amasezerano mashya yasinywe',
        'Unit after move-out': 'Icyumba nyuma yo kwimuka',
        Deposit: 'Ingwate',
        'Previous agreements remain available for audit and financial history.': 'Amasezerano yabanje aracyaboneka mu igenzura no mu mateka y’amafaranga.',
        'Rent/deposit payments recorded': 'Ubwishyu bw’ubukode/ingwate bwanditswe',
        'Tenancy history': 'Amateka y’ubukode',
        received: 'yakiriwe',
        available: 'kirahari',
        occupied: 'kirimo umukodesha',
        maintenance: 'kirimo gusanwa',
        reserved: 'cyarabitswe',
        inactive: 'ntigikora',
        active: 'kirakora',
        scheduled: 'giteganyijwe',
        ended: 'cyarangiye',
        cancelled: 'cyahagaritswe',
    },
};
