export default {
    fr: {
        'Lease documents': 'Documents de bail',
        'Signed agreements and renewals attached to your tenancies.': 'Contrats signés et renouvellements associés à vos locations.',
        Tenant: 'Locataire',
        'Property / unit': 'Bien / unité',
        'Lease term': 'Durée du bail',
        'Payments due to date': 'Paiements dus à ce jour',
        'Rent due': 'Loyer dû',
        'Deposit due': 'Dépôt dû',
        'Damage charge due': 'Frais de dommages dus',
        Uploaded: 'Téléversé le',
        Ongoing: 'En cours',
        Unknown: 'Inconnu',
        Download: 'Télécharger',
        Unavailable: 'Indisponible',
        'Manage tenancy': 'Gérer la location',
        'No lease documents yet': 'Aucun document de bail',
        'Upload signed agreements from a unit’s tenancy section.': 'Téléversez les contrats signés depuis la section location de l’unité.',
        'Browse properties': 'Parcourir les biens',
        'outstanding': 'impayé',
        'Rent & deposit payments': 'Paiements du loyer et du dépôt',
        'Agreement payment report': 'Rapport des paiements du contrat',
        'Agreement balances, payments received, and time remaining.': 'Soldes du contrat, paiements reçus et durée restante.',
        'Print payment report': 'Imprimer le rapport des paiements',
        'Remaining balance (deposit credit)': 'Solde restant (crédit du dépôt)',
        'Payment details': 'Détails du paiement',
        'Manage / renew': 'Gérer / renouveler',
        'Remaining balance is the refundable deposit credit still held after move-out refunds and damage deductions. It is separate from rent owed and may carry into a renewal.': 'Le solde restant est le crédit de dépôt remboursable après remboursement au départ et déductions pour dommages. Il est distinct du loyer dû et peut être reporté lors du renouvellement.',
        'Search individual payments and print a receipt for each payment.': 'Recherchez les paiements individuels et imprimez un reçu pour chacun.',
        'Each recorded payment has one receipt, even when it covers several rent periods.': 'Chaque paiement enregistré possède un seul reçu, même s’il couvre plusieurs périodes de loyer.',
        'Each row shows one payment and its receipt.': 'Chaque ligne présente un paiement et son reçu.',
        'Recorded payments and receipts will appear here.': 'Les paiements enregistrés et leurs reçus apparaîtront ici.',
        'Periods covered': 'Périodes couvertes',
        ':count rent periods': ':count périodes de loyer',
        'Outstanding rent across :count periods. One payment can cover several periods; it is applied to the oldest balance first and creates one receipt.': 'Loyer restant sur :count périodes. Un paiement peut couvrir plusieurs périodes ; il est appliqué au solde le plus ancien et génère un seul reçu.',
        'Record rent payment': 'Enregistrer un paiement de loyer',
        'Record one payment': 'Enregistrer un seul paiement',
        'One payment covers :count rent periods': 'Un paiement couvre :count périodes de loyer',
        'Payment transactions': 'Transactions de paiement',
        'Each row is one separately recorded payment.': 'Chaque ligne correspond à un paiement enregistré séparément.',
        'Search tenant, agreement, receipt, reference...': 'Rechercher un locataire, contrat, reçu, référence...',
        'Search payments': 'Rechercher des paiements',
        'Agreement / tenant': 'Contrat / locataire',
        'Payment date': 'Date du paiement',
        'Amount paid': 'Montant payé',
        'Payment method / reference': 'Mode de paiement / référence',
        'Agreement total paid': 'Total payé pour le contrat',
        'No payments match your search.': 'Aucun paiement ne correspond à votre recherche.',
        'No payments recorded yet.': 'Aucun paiement enregistré.',
        'Try searching by tenant, agreement ID, receipt number, or transaction reference.': 'Essayez de rechercher par locataire, identifiant du contrat, numéro de reçu ou référence de transaction.',
        'Recorded rent and deposit payments will appear here as individual rows.': 'Les paiements de loyer et de dépôt enregistrés apparaîtront ici sur des lignes individuelles.',
        'Showing :from to :to of :total payments': 'Affichage de :from à :to sur :total paiements',
        'Taxable rent before VAT': 'Loyer imposable hors TVA',
        'VAT calculated on rent received (:rate%)': 'TVA calculée sur les loyers reçus (:rate %)',
        'VAT included (18%)': 'TVA incluse (18 %)',
        'Amount received': 'Montant reçu',
        'Recorded rent amount': 'Montant du loyer enregistré',
        'VAT at :rate% of amount': 'TVA à :rate % du montant',
        'VAT included': 'TVA incluse',
        'VAT breakdown not recorded': 'Détail de TVA non enregistré',
        'Not recorded': 'Non enregistré',
        ':count older rent payments do not have a saved VAT breakdown and are excluded from the VAT totals.': ':count anciens paiements de loyer ne comportent pas de détail de TVA enregistré et sont exclus des totaux de TVA.',
        'VAT is calculated at the configured Rwanda rate on the recorded rent amount and shown separately. The recorded payment amount is unchanged. Confirm tax applicability and registration with the Rwanda Revenue Authority; this management report is not a VAT invoice or tax return.': 'La TVA est calculée au taux rwandais configuré sur le montant du loyer enregistré et affichée séparément. Le montant du paiement enregistré reste inchangé. Vérifiez l’assujettissement et l’immatriculation auprès de l’Office rwandais des recettes ; ce rapport de gestion n’est ni une facture TVA ni une déclaration fiscale.',
        'This payment receipt is not a VAT invoice or tax return.': 'Ce reçu de paiement n’est ni une facture TVA ni une déclaration fiscale.',
        'Track charges, record partial or full payments, and issue receipts.': 'Suivez les frais, enregistrez les paiements partiels ou complets et émettez des reçus.',
        'Track charges and record payments. To print a receipt, find a saved payment below and select Print receipt beside it.': 'Suivez les frais et enregistrez les paiements. Pour imprimer un reçu, trouvez un paiement enregistré ci-dessous et sélectionnez Imprimer le reçu à côté.',
        'Print receipt': 'Imprimer le reçu',
        'Payment receipt': 'Reçu de paiement',
        'Date paid': 'Date du paiement',
        'Received from': 'Reçu de',
        Charge: 'Frais',
        'Amount received': 'Montant reçu',
        Note: 'Note',
        'Thank you for your payment.': 'Merci pour votre paiement.',
        'All charges': 'Tous les frais',
        Outstanding: 'Impayés',
        Overdue: 'En retard',
        Paid: 'Payé',
        Cancelled: 'Annulé',
        Remaining: 'Restant',
        'Paid in full': 'Entièrement payé',
        'Amount (max :amount RWF)': 'Montant (maximum :amount RWF)',
        'Payment method': 'Mode de paiement',
        'Deposit payment method': 'Mode de paiement du dépôt',
        'The full security deposit will be recorded as paid using this method.': 'Le dépôt de garantie complet sera enregistré comme payé avec ce mode de paiement.',
        'Payment reference': 'Référence de paiement',
        'Transaction reference': 'Référence de transaction',
        'External transaction reference': 'Référence de transaction externe',
        Receipt: 'Reçu',
        'App receipt number': 'Numéro de reçu de l’application',
        'No transaction reference recorded': 'Aucune référence de transaction enregistrée',
        'Payment history': 'Historique des paiements',
        'Agreement reference not available': 'Référence du contrat indisponible',
        'Bank / Mobile Money transaction ID': 'Référence bancaire / identifiant de transaction Mobile Money',
        'Payment transaction references': 'Références des transactions de paiement',
        'Receipt pending': 'Reçu en attente',
        'Bank payment reference': 'Référence du paiement bancaire',
        'Mobile money transaction ID': 'Identifiant de transaction Mobile Money',
        Cash: 'Espèces',
        'Bank transfer': 'Virement bancaire',
        'Mobile money': 'Mobile Money',
        Other: 'Autre',
        'Received at': 'Reçu le',
        'Reference (optional)': 'Référence (facultatif)',
        'Payment note (optional)': 'Note de paiement (facultatif)',
        'Saving payment…': 'Enregistrement du paiement…',
        'Record payment': 'Enregistrer le paiement',
        'No charges found': 'Aucun frais trouvé',
        'Rent and deposit charges are created from the tenancy schedule.': 'Les frais de loyer et de dépôt sont créés selon le calendrier de location.',
        'View properties': 'Voir les biens',
        'Portfolio reports': 'Rapports du portefeuille',
        'Finance at a glance': 'Aperçu des finances',
        'Live portfolio summary': 'Résumé actualisé du portefeuille',
        'Financial performance': 'Performance financière',
        'Portfolio-wide payment and VAT summary': 'Résumé des paiements et de la TVA du portefeuille',
        'Across all recorded payment types': 'Tous les types de paiements enregistrés',
        'Recorded rent payments': 'Paiements de loyer enregistrés',
        'Deposit currently held': 'Dépôt actuellement détenu',
        'Cash flow': 'Flux de trésorerie',
        'Total VAT payable': 'Total de la TVA à payer',
        'Calculated at :rate% on recorded taxable payments': 'Calculée à :rate % sur les paiements imposables enregistrés',
        'Monthly rent and VAT': 'Loyer mensuel et TVA',
        'Recorded rent payments and their calculated VAT for the last six months.': 'Paiements de loyer enregistrés et TVA calculée pour les six derniers mois.',
        'Rent received · 6 months': 'Loyer reçu · 6 mois',
        'VAT payable · 6 months': 'TVA à payer · 6 mois',
        'Last six months': 'Six derniers mois',
        'Monthly rent and VAT for the last six months': 'Loyer mensuel et TVA pour les six derniers mois',
        'Rent received': 'Loyer reçu',
        'VAT payable': 'TVA à payer',
        'Finance chart': 'Graphique financier',
        'Compare recorded rent, VAT, and refundable deposit': 'Comparer le loyer enregistré, la TVA et le dépôt remboursable',
        'Recorded rent': 'Loyer enregistré',
        'VAT is calculated at :rate% of recorded rent and shown separately.': 'La TVA est calculée à :rate % du loyer enregistré et présentée séparément.',
        'VAT payable': 'TVA à payer',
        'Rent received': 'Loyer reçu',
        'Print report': 'Imprimer le rapport',
        'Total payments received': 'Total des paiements reçus',
        'Refundable deposit credit': 'Dépôt remboursable restant',
        'Agreement ID': 'Identifiant du contrat',
        'Tenant / property': 'Locataire / bien',
        'Agreement term': 'Durée du contrat',
        'Total paid': 'Total payé',
        'Deposit credit': 'Crédit de dépôt',
        'Days remaining': 'Jours restants',
        'Agreement financial details will appear here when a tenancy is created.': 'Les informations financières du contrat apparaîtront ici une fois le bail créé.',
        'Deposit credit is the deposit still held for the current agreement chain after refunds and damage deductions. It is separate from rent payments and may carry into a renewal.': 'Le crédit de dépôt correspond au montant détenu après remboursements et déductions pour dommages. Il est distinct des loyers et peut être reporté au renouvellement.',
        'Damage cost (RWF)': 'Coût des dommages (RWF)',
        'Deposit refund': 'Remboursement du dépôt',
        'Additional damage amount due': 'Supplément dû pour les dommages',
        'Damage costs will be deducted from the deposit.': 'Les dommages seront déduits du dépôt.',
        'A current overview of occupancy, leases, charges, and money received.': 'Vue actuelle de l’occupation, des baux, des frais et des paiements reçus.',
        'Occupancy rate': 'Taux d’occupation',
        'Active leases': 'Baux actifs',
        'Expiring in 30 days': 'Expirant dans 30 jours',
        'Collected this month': 'Montant encaissé ce mois',
        'Remaining rent / damage charges': 'Loyers / dommages restant dus',
        'Past-due rent / damage charges': 'Loyers / dommages échus',
        'Property occupancy': 'Occupation des biens',
        'Manage properties': 'Gérer les biens',
        Units: 'Unités',
        Occupancy: 'Occupation',
        Available: 'Disponibles',
        'Current tenants': 'Locataires actuels',
        'No active tenants': 'Aucun locataire actif',
        'Add a property to start seeing portfolio reports.': 'Ajoutez un bien pour commencer à voir les rapports du portefeuille.',
        'Review lease documents': 'Consulter les documents de bail',
        'Review payments': 'Consulter les paiements',
        'Create tenant': 'Créer un locataire',
        'Identity and contact details are required for all tenants.': 'Les informations d’identité et de contact sont requises pour tous les locataires.',
        Identity: 'Identité',
        Contact: 'Contact',
        'Active units': 'Unités actives',
        Property: 'Bien',
        Action: 'Action',
        Passport: 'Passeport',
        ID: 'Pièce d’identité',
        Representative: 'Représentant',
        'No email': 'Aucun e-mail',
        'View & assign': 'Voir et attribuer',
        'No :status charges found': 'Aucun frais :status trouvé',
        Payment: 'Paiement',
        Unit: 'Unité',
        'Due': 'À payer',
        'Up to date': 'À jour',
        'Partially paid': 'Partiellement payé',
        'Expiring soon': 'Expire bientôt',
        Scheduled: 'Programmé',
        Ended: 'Terminé',
        Expired: 'Expiré',
        rent: 'loyer',
        deposit: 'dépôt',
        damage: 'dommages',
        ':occupied occupied of :total total units': ':occupied occupées sur :total unités au total',
        'Assign this tenant to a unit': 'Attribuer ce locataire à une unité',
        'Choose an available unit, confirm the lease terms, and upload the signed lease. The unit will be reserved for a future start date.': 'Choisissez une unité disponible, confirmez les conditions du bail et téléversez le bail signé. L’unité sera réservée pour une date de début ultérieure.',
        'Available unit': 'Unité disponible',
        'Select a property and unit': 'Sélectionnez un bien et une unité',
        'Lease start date': 'Date de début du bail',
        'Lease end date': 'Date de fin du bail',
        'Rent frequency': 'Fréquence du loyer',
        Daily: 'Quotidien',
        Weekly: 'Hebdomadaire',
        Monthly: 'Mensuel',
        Quarterly: 'Trimestriel',
        Yearly: 'Annuel',
        'Rent per period (RWF)': 'Loyer par période (RWF)',
        'Monthly due day': 'Jour d’échéance mensuel',
        'Number of rent periods': 'Nombre de périodes de loyer',
        'Total rent for lease (RWF)': 'Loyer total du bail (RWF)',
        'Combined rent payment': 'Paiement de loyer combiné',
        'Periods included': 'Périodes incluses',
        'Rent period': 'Période de loyer',
        'One combined bill covers :count rent periods': 'Une facture combinée couvre :count périodes de loyer',
        'Each started rent period is charged in full. The security deposit is separate.': 'Toute période de loyer commencée est facturée en totalité. Le dépôt de garantie est séparé.',
        'Security deposit (RWF)': 'Dépôt de garantie (RWF)',
        'Signed lease document (required)': 'Document de bail signé (obligatoire)',
        'Notes (optional)': 'Notes (facultatif)',
        'Lease note (optional)': 'Note de bail (facultative)',
        'Agreement reference': 'Référence du contrat',
        'Generated automatically after saving': 'Générée automatiquement après l’enregistrement',
        'Select a payment method': 'Sélectionnez un mode de paiement',
        Reference: 'Référence',
        'Generate note with AI': 'Générer une note avec l’IA',
        'Generating note…': 'Génération de la note…',
        'Add context for this lease document, or generate a draft to edit.': 'Ajoutez du contexte à ce document de bail ou générez un brouillon à modifier.',
        'Names and identifying details are not sent to the AI service.': 'Les noms et les informations d’identification ne sont pas envoyés au service d’IA.',
        'Note generated. Review and edit it before saving.': 'Note générée. Vérifiez-la et modifiez-la avant de l’enregistrer.',
        'AI is unavailable; a template note was created. Review and edit it before saving.': 'L’IA est indisponible ; une note modèle a été créée. Vérifiez-la et modifiez-la avant de l’enregistrer.',
        'The note generator returned an empty response.': 'Le générateur de notes a renvoyé une réponse vide.',
        'Could not generate a lease note. Please try again.': 'Impossible de générer la note de bail. Veuillez réessayer.',
        'Tenancy notes (optional)': 'Notes de location (facultatives)',
        'Tenant identity and contact details will be reused from this profile.': 'Les informations d’identité et de contact du locataire seront reprises de ce profil.',
        'Saving tenancy…': 'Enregistrement de la location…',
        'Assign unit and create lease': 'Attribuer l’unité et créer le bail',
        'No available units right now': 'Aucune unité disponible pour le moment',
        'Create or make a unit available, then return here to assign it to :name.': 'Créez ou libérez une unité, puis revenez ici pour l’attribuer à :name.',
        'Full name': 'Nom complet',
        'Company registration number': 'Numéro d’enregistrement de l’entreprise',
        'Company name': 'Nom de l’entreprise',
        'Company TIN': 'NIF de l’entreprise',
        'Representative full name': 'Nom complet du représentant',
        Province: 'Province',
        District: 'District',
        Sector: 'Secteur',
        'Select Province': 'Sélectionner une province',
        'Select District': 'Sélectionner un district',
        'Select Sector': 'Sélectionner un secteur',
        'Enter 10 digits starting with 078, 072, or 073.': 'Saisissez 10 chiffres commençant par 078, 072 ou 073.',
        'Unable to load locations. Please try again.': 'Impossible de charger les lieux. Veuillez réessayer.',
        'Identity type': 'Type de pièce d’identité',
        'Identity number': 'Numéro d’identité',
        'National ID number': 'Numéro de carte d’identité nationale',
        'National ID': 'Carte d’identité nationale',
        'Passport number': 'Numéro de passeport',
        'Representative national ID number': 'Numéro de carte d’identité nationale du représentant',
        'Representative passport number': 'Numéro de passeport du représentant',
        'Save tenant details': 'Enregistrer les informations du locataire',
        'No unit has been assigned to this tenant yet. Use the assignment form above to get started.': 'Aucune unité n’a encore été attribuée à ce locataire. Utilisez le formulaire ci-dessus pour commencer.',
        Collected: 'Encaissé',
        'Open unit': 'Ouvrir l’unité',
        'Add Unit to :property': 'Ajouter une unité à :property',
        'Add Unit': 'Ajouter une unité',
        'Back to Units': 'Retour aux unités',
        'Unit Information': 'Informations sur l’unité',
        'Unit Number': 'Numéro de l’unité',
        'e.g., A-101, B-205': 'ex. : A-101, B-205',
        'Unit Type': 'Type d’unité',
        'Select Unit Type': 'Sélectionnez un type d’unité',
        '0 for ground floor, 1 for first floor': '0 pour le rez-de-chaussée, 1 pour le premier étage',
        'Monthly Rent (RWF)': 'Loyer mensuel (RWF)',
        'e.g., 150000': 'ex. : 150000',
        'Rent Frequency': 'Fréquence du loyer',
        'Unit Size (m²)': 'Surface de l’unité (m²)',
        'e.g., 60': 'ex. : 60',
        'Describe the unit features, amenities, etc.': 'Décrivez les caractéristiques et équipements de l’unité.',
        Maintenance: 'Maintenance',
        Reserved: 'Réservée',
        Inactive: 'Inactive',
        'Unit Images': 'Images de l’unité',
        'Add up to 10 JPG, PNG, GIF, or WebP images. Maximum 2 MB each.': 'Ajoutez jusqu’à 10 images JPG, PNG, GIF ou WebP. 2 Mo maximum chacune.',
        'Select images': 'Sélectionner des images',
        'Creating...': 'Création...',
        'Create Unit': 'Créer l’unité',
        'Edit Unit - :number': 'Modifier l’unité - :number',
        'Updating...': 'Mise à jour...',
        'Update Unit': 'Mettre à jour l’unité',
        'Cover image': 'Image de couverture',
        'Unit image': 'Image de l’unité',
        'Remove unit image': 'Supprimer l’image de l’unité',
        'Search properties...': 'Rechercher des biens...',
        'Add Property': 'Ajouter un bien',
        'No properties found': 'Aucun bien trouvé',
        'Try adjusting your search filters': 'Essayez de modifier vos filtres de recherche',
        'Get started by adding your first property': 'Commencez par ajouter votre premier bien',
        Occupied: 'Occupé',
        Maint: 'Maintenance',
        'Created by:': 'Créé par :',
        'Reg.': 'Enr.',
        Parking: 'Stationnement',
        Security: 'Sécurité',
        Gym: 'Salle de sport',
        Pool: 'Piscine',
        Restaurant: 'Restaurant',
        Bar: 'Bar',
        unit: 'unité',
        units: 'unités',
        ':count :unit': ':count :unit',
        View: 'Voir',
        'Showing :from to :to of :total properties': 'Affichage de :from à :to sur :total biens',
        'Delete Property': 'Supprimer le bien',
        'Are you sure you want to delete :name? This action cannot be undone and will also delete all associated units and images.': 'Voulez-vous vraiment supprimer :name ? Cette action est irréversible et supprimera également toutes les unités et images associées.',
        Delete: 'Supprimer',
        'Unit and tenancy history': 'Historique des unités et locations',
        'Current, upcoming, and previous leases for this tenant.': 'Baux actuels, à venir et précédents de ce locataire.',
        'Move-out deposit': 'Dépôt de garantie au départ',
        refunded: 'remboursé',
        deducted: 'déduit',
        ':property - Units': ':property - unités',
        Actions: 'Actions',
        'All Status': 'Tous les statuts',
        'Assign tenant': 'Attribuer un locataire',
        'Back to Property': 'Retour au bien',
        'New Tenant': 'Nouveau locataire',
        'No units found': 'Aucune unité trouvée',
        'Search units...': 'Rechercher des unités...',
        Size: 'Surface',
        ':type charge': 'Frais :type',
        ':unit - Details': ':unit - détails',
        'A renewal is scheduled to start on :date; it will activate automatically on that date.': 'Un renouvellement est prévu le :date ; il sera activé automatiquement à cette date.',
        Cell: 'Cellule',
        District: 'District',
        'Due / overdue balance': 'Solde dû / en retard',
        'Edit Unit': 'Modifier l’unité',
        'Edit this Unit': 'Modifier cette unité',
        'Go to Property': 'Aller au bien',
        'Ledger charges': 'Frais du registre',
        Method: 'Mode',
        'Monthly Rent': 'Loyer mensuel',
        'No leases uploaded yet.': 'Aucun bail téléversé pour le moment.',
        'No rent charges yet. Scheduled charge generation will fill missing periods automatically.': 'Aucun frais de loyer pour le moment. La génération planifiée ajoutera automatiquement les périodes manquantes.',
        'Optional note': 'Note facultative',
        'PDF, DOC, DOCX, JPG, JPEG or PNG. Maximum 10 MB.': 'PDF, DOC, DOCX, JPG, JPEG ou PNG. 10 Mo maximum.',
        'Paid at': 'Payé le',
        'Payment amount': 'Montant du paiement',
        'Property Location': 'Emplacement du bien',
        Province: 'Province',
        'Quick Actions': 'Actions rapides',
        'Renew lease': 'Renouveler le bail',
        'Rent and deposit ledger': 'Registre des loyers et dépôts',
        'Rent per period': 'Loyer par période',
        'Size (m²)': 'Surface (m²)',
        Starts: 'Commence le',
        'Tenancy & lease': 'Location et bail',
        'The next term is linked to this tenancy. Its deposit carries forward without being charged again.': 'La prochaine période est liée à cette location. Le dépôt est reporté sans être facturé à nouveau.',
        'The unit is reserved and will become occupied automatically on the start date.': 'L’unité est réservée et sera automatiquement occupée à la date de début.',
        'Unit :unit': 'Unité :unit',
        'Unit Details': 'Détails de l’unité',
        'Upcoming move-in scheduled': 'Emménagement à venir programmé',
        'Upload another signed lease or amendment': 'Téléverser un autre bail signé ou un avenant',
        'Upload lease': 'Téléverser le bail',
        'Uploading…': 'Téléversement…',
        'View All Units': 'Voir toutes les unités',
        to: 'au',
        'Are you sure you want to delete unit :unit? This action cannot be undone.': 'Voulez-vous vraiment supprimer l’unité :unit ? Cette action est irréversible.',
        'Create tenancy': 'Créer la location',
        'Create tenancy for :unit': 'Créer une location pour :unit',
        'Delete Unit': 'Supprimer l’unité',
        Notes: 'Notes',
        'Residential / business address': 'Adresse résidentielle / professionnelle',
        'Showing :from to :to of :total units': 'Affichage de :from à :to sur :total unités',
        'Signed lease (PDF, DOC, DOCX, JPG or PNG)': 'Bail signé (PDF, DOC, DOCX, JPG ou PNG)',
        'Tenancy end date': 'Date de fin de location',
        'Tenancy start date': 'Date de début de location',
        'Tenant identity, contact information, signed lease, and rent terms are required.': 'L’identité du locataire, ses coordonnées, le bail signé et les conditions de loyer sont requis.',
        'The first full rent period starts on the tenancy start date.': 'La première période complète de loyer commence à la date de début de location.',
        'Condition / inspection notes': 'Notes sur l’état / l’inspection',
        'Deduction explanation': 'Justification des retenues',
        'Deductions (RWF)': 'Déductions (RWF)',
        'Deposit received': 'Dépôt reçu',
        'Due day': 'Jour d’échéance',
        'Move-out date': 'Date de départ',
        'Move-out inspection': 'Inspection de départ',
        'Needs maintenance': 'Nécessite un entretien',
        'New lease end': 'Fin du nouveau bail',
        'New lease start': 'Début du nouveau bail',
        'Record the unit condition and reconcile all received deposits before closing the tenancy.': 'Consignez l’état de l’unité et rapprochez tous les dépôts reçus avant de clôturer la location.',
        'Refund (RWF)': 'Remboursement (RWF)',
        'Save renewal': 'Enregistrer le renouvellement',
        'Signed renewal lease': 'Bail de renouvellement signé',
        'Unit after move-out': 'État de l’unité après le départ',
        Deposit: 'Dépôt',
        'Previous agreements remain available for audit and financial history.': 'Les contrats précédents restent disponibles pour le suivi et l’historique financier.',
        'Rent/deposit payments recorded': 'Paiements de loyer/dépôt enregistrés',
        'Tenancy history': 'Historique de location',
        received: 'reçu',
        available: 'disponible',
        occupied: 'occupé',
        maintenance: 'maintenance',
        reserved: 'réservé',
        inactive: 'inactif',
        active: 'actif',
        scheduled: 'programmé',
        ended: 'terminé',
        cancelled: 'annulé',
    },
    rw: {
        'Lease documents': 'Inyandiko z’amasezerano',
        'Signed agreements and renewals attached to your tenancies.': 'Amasezerano yasinywe n’ayongereweho ajyanye n’ubukode bwawe.',
        Tenant: 'Ukodesha',
        'Property / unit': 'Inzu / icyumba',
        'Lease term': 'Igihe cy’amasezerano',
        'Payments due to date': 'Amafaranga agomba kwishyurwa kugeza ubu',
        'Rent due': 'Ubukode bugomba kwishyurwa',
        'Deposit due': 'Ingwate igomba kwishyurwa',
        'Damage charge due': 'Amafaranga y’ibyangiritse agomba kwishyurwa',
        Uploaded: 'Byashyizweho',
        Ongoing: 'Birakomeza',
        Unknown: 'Ntibizwi',
        Download: 'Manura',
        Unavailable: 'Ntibiboneka',
        'Manage tenancy': 'Genzura ubukode',
        'No lease documents yet': 'Nta nyandiko z’amasezerano zirahari',
        'Upload signed agreements from a unit’s tenancy section.': 'Shyira amasezerano yasinywe mu gice cy’ubukode bw’icyumba.',
        'Browse properties': 'Reba inzu',
        'outstanding': 'asigaye kwishyurwa',
        'Rent & deposit payments': 'Ubukode n’amafaranga y’ingwate',
        'Agreement payment report': 'Raporo y’ubwishyu bw’amasezerano',
        'Agreement balances, payments received, and time remaining.': 'Amafaranga asigaye ku masezerano, ayishyuwe n’igihe gisigaye.',
        'Print payment report': 'Sohora raporo y’ubwishyu',
        'Remaining balance (deposit credit)': 'Amafaranga asigaye ku ngwate',
        'Payment details': 'Ibisobanuro by’ubwishyu',
        'Search individual payments and print a receipt for each payment.': 'Shakisha buri bwishyu kandi usohore inyemezabwishyu yabwo.',
        'Each recorded payment has one receipt, even when it covers several rent periods.': 'Buri bwishyu bwanditswe bugira inyemezabwishyu imwe, nubwo bwishyura ibihe byinshi by’ubukode.',
        'Each row shows one payment and its receipt.': 'Buri murongo ugaragaza ubwishyu bumwe n’inyemezabwishyu yabwo.',
        'Recorded payments and receipts will appear here.': 'Ubwishyu bwanditswe n’inyemezabwishyu zabwo bizagaragara hano.',
        'Periods covered': 'Ibihe byishyuwe',
        ':count rent periods': 'Ibihe :count by’ubukode',
        'Outstanding rent across :count periods. One payment can cover several periods; it is applied to the oldest balance first and creates one receipt.': 'Ubukode busigaye mu bihe :count. Ubwishyu bumwe bushobora kwishyura ibihe byinshi; bubanza kwishyura umwenda wa kera kandi bugatanga inyemezabwishyu imwe.',
        'Record rent payment': 'Andika ubwishyu bw’ubukode',
        'Record one payment': 'Andika ubwishyu bumwe',
        'One payment covers :count rent periods': 'Ubwishyu bumwe bwishyuye ibihe :count by’ubukode',
        'Payment transactions': 'Ibikorwa by’ubwishyu',
        'Each row is one separately recorded payment.': 'Buri murongo ugaragaza ubwishyu bumwe bwanditswe ukwabwo.',
        'Search tenant, agreement, receipt, reference...': 'Shakisha ukodesha, amasezerano, inyemezabwishyu cyangwa nomero...',
        'Search payments': 'Shakisha ubwishyu',
        'Agreement / tenant': 'Amasezerano / ukodesha',
        'Payment date': 'Itariki yo kwishyura',
        'Amount paid': 'Amafaranga yishyuwe',
        'Payment method / reference': 'Uburyo bwo kwishyura / nomero',
        'Agreement total paid': 'Igiteranyo cyishyuwe ku masezerano',
        'No payments match your search.': 'Nta bwishyu bujyanye n’ishakisha.',
        'No payments recorded yet.': 'Nta bwishyu burandikwa.',
        'Try searching by tenant, agreement ID, receipt number, or transaction reference.': 'Shakisha ukoresheje ukodesha, nomero y’amasezerano, inyemezabwishyu cyangwa nomero y’igikorwa.',
        'Recorded rent and deposit payments will appear here as individual rows.': 'Ubwishyu bw’ubukode n’ingwate buzagaragara hano buri bwishyu ukwabwo.',
        'Showing :from to :to of :total payments': 'Herekanwa :from kugeza :to kuri :total byishyuwe',
        'Taxable rent before VAT': 'Ubukode butarimo umusoro ku nyongeragaciro',
        'VAT calculated on rent received (:rate%)': 'Umusoro ku nyongeragaciro ubarwa ku bukode bwakiriwe (:rate%)',
        'VAT included (18%)': 'Umusoro ku nyongeragaciro urimo (18%)',
        'Amount received': 'Amafaranga yakiriwe',
        'Recorded rent amount': 'Amafaranga y’ubukode yanditswe',
        'VAT at :rate% of amount': 'Umusoro wa :rate% ku mafaranga',
        'VAT included': 'Umusoro ku nyongeragaciro urimo',
        'VAT breakdown not recorded': 'Ibisobanuro by’umusoro ntibyanditswe',
        'Not recorded': 'Ntibyanditswe',
        ':count older rent payments do not have a saved VAT breakdown and are excluded from the VAT totals.': 'Ubwishyu bw’ubukode :count bwa kera nta bisobanuro by’umusoro bwanditseho kandi ntibubarwa mu musoro wose.',
        'VAT is calculated at the configured Rwanda rate on the recorded rent amount and shown separately. The recorded payment amount is unchanged. Confirm tax applicability and registration with the Rwanda Revenue Authority; this management report is not a VAT invoice or tax return.': 'Umusoro ubarwa ku gipimo cy’u Rwanda cyashyizweho hashingiwe ku mafaranga y’ubukode yanditswe kandi ukerekanwa ukwawo. Amafaranga y’ubwishyu yanditswe ntahinduka. Emeza ko ugomba gukoreshwa n’iyandikwa muri RRA; iyi raporo si inyemezabwishyu y’umusoro cyangwa imenyekanisha ry’umusoro.',
        'This payment receipt is not a VAT invoice or tax return.': 'Iyi nyemezabwishyu si inyemezabwishyu y’umusoro cyangwa imenyekanisha ry’umusoro.',
        'Manage / renew': 'Genzura / ongera amasezerano',
        'Remaining balance is the refundable deposit credit still held after move-out refunds and damage deductions. It is separate from rent owed and may carry into a renewal.': 'Amafaranga asigaye ni ingwate ishobora gusubizwa nyuma yo gusubiza amafaranga no gukuramo ayo kwishyura ibyangiritse. Atandukanye n’ubukode busigaye kandi ashobora kujya mu masezerano mashya.',
        'Track charges, record partial or full payments, and issue receipts.': 'Kurikirana amafaranga agomba kwishyurwa, andika ayishyuwe yose cyangwa igice, utange inyemezabwishyu.',
        'All charges': 'Amafaranga yose',
        Outstanding: 'Asigaye',
        Overdue: 'Yarengeje igihe',
        Paid: 'Yishyuwe',
        Cancelled: 'Byahagaritswe',
        Remaining: 'Asigaye',
        'Paid in full': 'Yishyuwe yose',
        'Amount (max :amount RWF)': 'Amafaranga (ntarengwa :amount RWF)',
        'Payment method': 'Uburyo bwo kwishyura',
        'Deposit payment method': 'Uburyo bwo kwishyura ingwate',
        'The full security deposit will be recorded as paid using this method.': 'Ingwate yose izandikwa nk’iyishyuwe hakoreshejwe ubu buryo bwo kwishyura.',
        'Payment reference': 'Nomero y’icyemezo cy’ubwishyu',
        'Transaction reference': 'Nomero y’igikorwa cy’ubwishyu',
        'External transaction reference': 'Nomero y’igikorwa cya banki cyangwa Mobile Money',
        Receipt: 'Inyemezabwishyu',
        'App receipt number': 'Nomero y’inyemezabwishyu ya porogaramu',
        'No transaction reference recorded': 'Nta nomero y’igikorwa yanditswe',
        'Payment history': 'Amateka y’ubwishyu',
        'Agreement reference not available': 'Nomero y’amasezerano ntiboneka',
        'Bank / Mobile Money transaction ID': 'Nomero ya banki / igikorwa cya Mobile Money',
        'Payment transaction references': 'Nomero z’ibikorwa byo kwishyura',
        'Receipt pending': 'Inyemezabwishyu itegerejwe',
        'Bank payment reference': 'Nomero y’ubwishyu bwa banki',
        'Mobile money transaction ID': 'Nomero y’igikorwa cya Mobile Money',
        Cash: 'Amafaranga mu ntoki',
        'Bank transfer': 'Kohereza kuri banki',
        'Mobile money': 'Mobile Money',
        Other: 'Ubundi',
        'Received at': 'Yakiriwe ku',
        'Reference (optional)': 'Inomero ibaranga (si ngombwa)',
        'Payment note (optional)': 'Ibisobanuro ku kwishyura (si ngombwa)',
        'Saving payment…': 'Birabikwa...',
        'Record payment': 'Andika ko yishyuwe',
        'No charges found': 'Nta mafaranga aboneka',
        'Rent and deposit charges are created from the tenancy schedule.': 'Amafaranga y’ubukode n’ingwate ategurwa hakurikijwe gahunda y’ubukode.',
        'View properties': 'Reba inzu',
        'Portfolio reports': 'Raporo z’imitungo',
        'Finance at a glance': 'Imiterere y’imari muri make',
        'Live portfolio summary': 'Incamake igezweho y’imitungo',
        'Financial performance': 'Imikorere y’imari',
        'Portfolio-wide payment and VAT summary': 'Incamake y’ubwishyu n’umusoro ku mutungo wose',
        'Across all recorded payment types': 'Mu buryo bwose bw’ubwishyu bwanditswe',
        'Recorded rent payments': 'Ubwishyu bw’ubukode bwanditswe',
        'Deposit currently held': 'Ingwate iri kubikwa ubu',
        'Cash flow': 'Uko amafaranga yinjira',
        'Total VAT payable': 'Umusoro wose ku nyongeragaciro ugomba kwishyurwa',
        'Calculated at :rate% on recorded taxable payments': 'Ubarwa kuri :rate% ku bwishyu bw’imisoro bwanditswe',
        'Monthly rent and VAT': 'Ubukode bwa buri kwezi n’umusoro',
        'Recorded rent payments and their calculated VAT for the last six months.': 'Ubwishyu bw’ubukode bwanditswe n’umusoro wabwo mu mezi atandatu ashize.',
        'Rent received · 6 months': 'Ubukode bwakiriwe · amezi 6',
        'VAT payable · 6 months': 'Umusoro ugomba kwishyurwa · amezi 6',
        'Last six months': 'Amezi atandatu ashize',
        'Monthly rent and VAT for the last six months': 'Ubukode bwa buri kwezi n’umusoro mu mezi atandatu ashize',
        'Rent received': 'Ubukode bwakiriwe',
        'VAT payable': 'Umusoro ku nyongeragaciro ugomba kwishyurwa',
        'Finance chart': 'Igishushanyo cy’imari',
        'Compare recorded rent, VAT, and refundable deposit': 'Gereranya ubukode bwanditswe, umusoro, n’ingwate isubizwa',
        'Recorded rent': 'Ubukode bwanditswe',
        'VAT is calculated at :rate% of recorded rent and shown separately.': 'Umusoro ubarwa kuri :rate% y’ubukode bwanditswe kandi ukerekanwa ukwawo.',
        'VAT payable': 'Umusoro ku nyongeragaciro ugomba kwishyurwa',
        'Rent received': 'Ubukode bwakiriwe',
        'Print report': 'Sohora raporo',
        'Total payments received': 'Amafaranga yose yakiriwe',
        'Refundable deposit credit': 'Ingwate isigaye gusubizwa',
        'Agreement ID': 'Nomero y’amasezerano',
        'Tenant / property': 'Ukodesha / inzu',
        'Agreement term': 'Igihe cy’amasezerano',
        'Total paid': 'Amafaranga yose yishyuwe',
        'Deposit credit': 'Ingwate isigaye',
        'Days remaining': 'Iminsi isigaye',
        'Agreement financial details will appear here when a tenancy is created.': 'Ibisobanuro by’imari y’amasezerano bizagaragara hano ubukode bumaze gushyirwaho.',
        'Deposit credit is the deposit still held for the current agreement chain after refunds and damage deductions. It is separate from rent payments and may carry into a renewal.': 'Ingwate isigaye ni amafaranga akibitswe nyuma yo gusubiza no gukuramo ay’ibyangiritse. Itandukanye n’ubukode kandi ishobora kujyanwa mu masezerano mashya.',
        'Damage cost (RWF)': 'Amafaranga y’ibyangiritse (RWF)',
        'Deposit refund': 'Amafaranga y’ingwate asubizwa',
        'Additional damage amount due': 'Ayandi mafaranga y’ibyangiritse agomba kwishyurwa',
        'Damage costs will be deducted from the deposit.': 'Amafaranga y’ibyangiritse azokurwa ku ngwate.',
        'A current overview of occupancy, leases, charges, and money received.': 'Incamake y’ubu y’ibyumba bikodeshejwe, amasezerano, amafaranga agomba kwishyurwa n’ayakiriwe.',
        'Occupancy rate': 'Igipimo cy’ibyumba bikodeshejwe',
        'Active leases': 'Amasezerano akora',
        'Expiring in 30 days': 'Azarangira mu minsi 30',
        'Collected this month': 'Amafaranga yakiriwe muri uku kwezi',
        'Remaining rent / damage charges': 'Amafaranga y’ubukode / ibyangiritse asigaye',
        'Past-due rent / damage charges': 'Amafaranga y’ubukode / ibyangiritse yarengeje igihe',
        'Property occupancy': 'Imikoreshereze y’inzu',
        'Manage properties': 'Genzura inzu',
        Units: 'Ibyumba',
        Occupancy: 'Ibyumba bikodeshejwe',
        Available: 'Birahari',
        'Current tenants': 'Abakodesha ubu',
        'No active tenants': 'Nta bakodesha bakora',
        'Add a property to start seeing portfolio reports.': 'Ongeraho inzu kugira ngo utangire kubona raporo z’imitungo.',
        'Review lease documents': 'Reba inyandiko z’amasezerano',
        'Review payments': 'Reba ibyishyuwe',
        'Create tenant': 'Ongeraho ukodesha',
        'Identity and contact details are required for all tenants.': 'Amakuru y’irangamuntu n’itumanaho arakenewe ku bakodesha bose.',
        Identity: 'Irangamuntu',
        Contact: 'Itumanaho',
        'Active units': 'Ibyumba bikora',
        Property: 'Inzu',
        Action: 'Igikorwa',
        Passport: 'Pasiporo',
        ID: 'Indangamuntu',
        Representative: 'Uhagarariye ikigo',
        'No email': 'Nta imeyili',
        'View & assign': 'Reba unashyireho',
        'No :status charges found': 'Nta mafaranga :status aboneka',
        Payment: 'Kwishyura',
        Unit: 'Icyumba',
        Due: 'Agomba kwishyurwa',
        'Up to date': 'Kugeza ubu nta yandi abereyemo',
        'Partially paid': 'Yishyuwe igice',
        'Expiring soon': 'Agiye kurangira vuba',
        Scheduled: 'Byateganyijwe',
        Ended: 'Byarangiye',
        Expired: 'Byarengeje igihe',
        rent: 'ubukode',
        deposit: 'ingwate',
        damage: 'ibyangiritse',
        ':occupied occupied of :total total units': ':occupied bikodeshejwe kuri :total ibyumba byose',
        'Assign this tenant to a unit': 'Shyira uyu mukodesha mu cyumba',
        'Choose an available unit, confirm the lease terms, and upload the signed lease. The unit will be reserved for a future start date.': 'Hitamo icyumba gihari, wemeze ibikubiye mu masezerano, ushyireho amasezerano yasinywe. Icyumba kizabikirwa itariki yo gutangira izaza.',
        'Available unit': 'Icyumba gihari',
        'Select a property and unit': 'Hitamo inzu n’icyumba',
        'Lease start date': 'Itariki amasezerano atangirira',
        'Lease end date': 'Itariki amasezerano arangirira',
        'Rent frequency': 'Inshuro z’ubukode',
        Daily: 'Buri munsi',
        Weekly: 'Buri cyumweru',
        Monthly: 'Buri kwezi',
        Quarterly: 'Buri mezi atatu',
        Yearly: 'Buri mwaka',
        'Rent per period (RWF)': 'Ubukode kuri buri gihe (RWF)',
        'Monthly due day': 'Umunsi wo kwishyura buri kwezi',
        'Number of rent periods': 'Umubare w’ibihe by’ubukode',
        'Total rent for lease (RWF)': 'Ubukode bwose mu gihe cy’amasezerano (RWF)',
        'Combined rent payment': 'Ubwishyu bw’ubukode buhurijwe hamwe',
        'Periods included': 'Ibihe birimo',
        'Rent period': 'Igihe cy’ubukode',
        'One combined bill covers :count rent periods': 'Inyemezabwishyu imwe ihuriweho ikubiyemo ibihe :count by’ubukode',
        'Each started rent period is charged in full. The security deposit is separate.': 'Igihe cyose cy’ubukode gitangiye cyishyurwa cyose. Ingwate ntiyabarirwamo.',
        'Security deposit (RWF)': 'Amafaranga y’ingwate (RWF)',
        'Signed lease document (required)': 'Inyandiko y’amasezerano yasinywe (irakenewe)',
        'Notes (optional)': 'Ibisobanuro (si ngombwa)',
        'Lease note (optional)': 'Icyitonderwa cy’amasezerano (si ngombwa)',
        'Agreement reference': 'Nomero y’amasezerano',
        'Generated automatically after saving': 'Ihita ikorwa nyuma yo kubika',
        'Select a payment method': 'Hitamo uburyo bwo kwishyura',
        Reference: 'Nomero',
        'Generate note with AI': 'Kora icyitonderwa ukoresheje AI',
        'Generating note…': 'Icyitonderwa kirakorwa…',
        'Add context for this lease document, or generate a draft to edit.': 'Ongeraho ibisobanuro kuri iyi nyandiko cyangwa ukore umushinga wo guhindura.',
        'Names and identifying details are not sent to the AI service.': 'Amazina n’amakuru agaragaza umuntu ntibyohererezwa serivisi ya AI.',
        'Note generated. Review and edit it before saving.': 'Icyitonderwa cyakozwe. Gisuzume kandi ugihindure mbere yo kubika.',
        'AI is unavailable; a template note was created. Review and edit it before saving.': 'AI ntiboneka; hakoreshejwe icyitegererezo. Gisuzume kandi ugihindure mbere yo kubika.',
        'The note generator returned an empty response.': 'Serivisi yakoze icyitonderwa yagaruye ibisubizo by’ubusa.',
        'Could not generate a lease note. Please try again.': 'Ntibyashobotse gukora icyitonderwa cy’amasezerano. Ongera ugerageze.',
        'Tenancy notes (optional)': 'Ibisobanuro by’ubukode (si ngombwa)',
        'Tenant identity and contact details will be reused from this profile.': 'Amakuru y’irangamuntu n’itumanaho by’ukodesha bizava muri iyi konti.',
        'Saving tenancy…': 'Turimo kubika ubukode...',
        'Assign unit and create lease': 'Shyira mu cyumba unakore amasezerano',
        'No available units right now': 'Nta byumba bihari ubu',
        'Create or make a unit available, then return here to assign it to :name.': 'Kora icyumba cyangwa ugishyire ku isoko, hanyuma ugaruke kugishyira kuri :name.',
        'Full name': 'Amazina yose',
        'Company registration number': 'Nomero y’iyandikisha ry’ikigo',
        'Company name': 'Izina ry’ikigo',
        'Company TIN': 'TIN y’ikigo',
        'Representative full name': 'Amazina yose y’uhagarariye ikigo',
        Province: 'Intara',
        District: 'Akarere',
        Sector: 'Umurenge',
        'Select Province': 'Hitamo intara',
        'Select District': 'Hitamo akarere',
        'Select Sector': 'Hitamo umurenge',
        'Enter 10 digits starting with 078, 072, or 073.': 'Andika imibare 10 itangizwa na 078, 072 cyangwa 073.',
        'Unable to load locations. Please try again.': 'Ntibishobotse gufungura aho hantu. Ongera ugerageze.',
        'Identity type': 'Ubwoko bw’indangamuntu',
        'Identity number': 'Nomero y’indangamuntu',
        'National ID number': 'Nomero y’indangamuntu',
        'National ID': 'Indangamuntu',
        'Passport number': 'Nomero ya pasiporo',
        'Representative national ID number': 'Nomero y’indangamuntu y’uhagarariye ikigo',
        'Representative passport number': 'Nomero ya pasiporo y’uhagarariye ikigo',
        'Save tenant details': 'Bika amakuru y’ukodesha',
        'No unit has been assigned to this tenant yet. Use the assignment form above to get started.': 'Nta cyumba kirashyirwa kuri uyu mukodesha. Koresha ifomu iri hejuru utangire.',
        Collected: 'Yishyuwe',
        'Open unit': 'Fungura icyumba',
        'Add Unit to :property': 'Ongeraho icyumba muri :property',
        'Add Unit': 'Ongeraho icyumba',
        'Back to Units': 'Subira ku byumba',
        'Unit Information': 'Amakuru y’icyumba',
        'Unit Number': 'Nomero y’icyumba',
        'e.g., A-101, B-205': 'urugero: A-101, B-205',
        'Unit Type': 'Ubwoko bw’icyumba',
        'Select Unit Type': 'Hitamo ubwoko bw’icyumba',
        '0 for ground floor, 1 for first floor': '0 ku igorofa ryo hasi, 1 ku rya mbere',
        'Monthly Rent (RWF)': 'Ubukode bw’ukwezi (RWF)',
        'e.g., 150000': 'urugero: 150000',
        'Rent Frequency': 'Inshuro z’ubukode',
        'Unit Size (m²)': 'Ingano y’icyumba (m²)',
        'e.g., 60': 'urugero: 60',
        'Describe the unit features, amenities, etc.': 'Sobanura ibiranga icyumba n’ibikoresho kirimo.',
        Maintenance: 'Birimo gusanwa',
        Reserved: 'Byabitswe',
        Inactive: 'Ntibikora',
        'Unit Images': 'Amafoto y’icyumba',
        'Add up to 10 JPG, PNG, GIF, or WebP images. Maximum 2 MB each.': 'Ongeraho amafoto agera ku 10 ya JPG, PNG, GIF cyangwa WebP. Ntarengwa ni 2 MB kuri buri foto.',
        'Select images': 'Hitamo amafoto',
        'Creating...': 'Turimo gukora...',
        'Create Unit': 'Kora icyumba',
        'Edit Unit - :number': 'Hindura icyumba - :number',
        'Updating...': 'Turimo kuvugurura...',
        'Update Unit': 'Vugurura icyumba',
        'Cover image': 'Ifoto y’ingenzi',
        'Unit image': 'Ifoto y’icyumba',
        'Remove unit image': 'Siba ifoto y’icyumba',
        'Search properties...': 'Shakisha inzu...',
        'Add Property': 'Ongeraho inzu',
        'No properties found': 'Nta nzu yabonetse',
        'Try adjusting your search filters': 'Gerageza guhindura ibyo washakishije',
        'Get started by adding your first property': 'Tangira wongeraho inzu ya mbere',
        Occupied: 'Kirakodeshwa',
        Maint: 'Birakorwa',
        'Created by:': 'Yakozwe na:',
        'Reg.': 'Kwiyandikisha',
        Parking: 'Aho guhagarika imodoka',
        Security: 'Umutekano',
        Gym: 'Aho gukorera imyitozo',
        Pool: 'Pisine',
        Restaurant: 'Resitora',
        Bar: 'Akabari',
        unit: 'icyumba',
        units: 'ibyumba',
        ':count :unit': ':count :unit',
        View: 'Reba',
        'Showing :from to :to of :total properties': 'Herekanwa :from kugeza :to kuri :total inzu',
        'Delete Property': 'Siba inzu',
        'Are you sure you want to delete :name? This action cannot be undone and will also delete all associated units and images.': 'Uremeza ko ushaka gusiba :name? Ntibishobora gusubirwaho kandi n’ibyumba n’amafoto biyifitanye isano birasibwa.',
        Delete: 'Siba',
        'Unit and tenancy history': 'Amateka y’ibyumba n’ubukode',
        'Current, upcoming, and previous leases for this tenant.': 'Amasezerano y’ubu, ateganyijwe n’ayabanje kuri uyu mukodesha.',
        'Move-out deposit': 'Ingwate igihe cyo kwimuka',
        refunded: 'yasubijwe',
        deducted: 'yakuwemo',
        ':property - Units': ':property - ibyumba',
        Actions: 'Ibikorwa',
        'All Status': 'Imiterere yose',
        'Assign tenant': 'Shyiraho umukodesha',
        'Back to Property': 'Subira ku nzu',
        'New Tenant': 'Umukodesha mushya',
        'No units found': 'Nta byumba byabonetse',
        'Search units...': 'Shakisha ibyumba...',
        Size: 'Ingano',
        ':type charge': 'Amafaranga ya :type',
        ':unit - Details': ':unit - ibisobanuro',
        'A renewal is scheduled to start on :date; it will activate automatically on that date.': 'Kongera amasezerano bizatangira ku wa :date kandi bizikora kuri uwo munsi.',
        Cell: 'Akagari',
        District: 'Akarere',
        'Due / overdue balance': 'Amafaranga agomba kwishyurwa cyangwa yarengeje igihe',
        'Edit Unit': 'Hindura icyumba',
        'Edit this Unit': 'Hindura iki cyumba',
        'Go to Property': 'Jya ku nzu',
        'Ledger charges': 'Amafaranga ategereje kwishyurwa',
        Method: 'Uburyo',
        'Monthly Rent': 'Ubukode bw’ukwezi',
        'No leases uploaded yet.': 'Nta masezerano yashyizweho.',
        'No rent charges yet. Scheduled charge generation will fill missing periods automatically.': 'Nta mafaranga y’ubukode arashyirwaho. Gahunda izongeraho ibihe byabuze mu buryo bwikora.',
        'Optional note': 'Icyitonderwa si ngombwa',
        'PDF, DOC, DOCX, JPG, JPEG or PNG. Maximum 10 MB.': 'PDF, DOC, DOCX, JPG, JPEG cyangwa PNG. Ntarengwa ni 10 MB.',
        'Paid at': 'Yishyuwe ku',
        'Payment amount': 'Amafaranga yishyuwe',
        'Property Location': 'Aho inzu iherereye',
        Province: 'Intara',
        'Quick Actions': 'Ibikorwa byihuse',
        'Renew lease': 'Ongera amasezerano',
        'Rent and deposit ledger': 'Ibaruramari ry’ubukode n’ingwate',
        'Rent per period': 'Ubukode kuri buri gihe',
        'Size (m²)': 'Ingano (m²)',
        Starts: 'Bitangira',
        'Tenancy & lease': 'Ubukode n’amasezerano',
        'The next term is linked to this tenancy. Its deposit carries forward without being charged again.': 'Igihe gikurikira gihuzwa n’ubu bukode. Ingwate irakomeza ntisubire kubarwa.',
        'The unit is reserved and will become occupied automatically on the start date.': 'Icyumba cyarabitswe kandi kizahita gikoreshwa ku itariki yo gutangira.',
        'Unit :unit': 'Icyumba :unit',
        'Unit Details': 'Ibisobanuro by’icyumba',
        'Upcoming move-in scheduled': 'Kwimukiramo guteganyijwe',
        'Upload another signed lease or amendment': 'Shyiraho andi masezerano yasinywe cyangwa inyongera yayo',
        'Upload lease': 'Shyiraho amasezerano',
        'Uploading…': 'Birashyirwaho…',
        'View All Units': 'Reba ibyumba byose',
        to: 'kugeza',
        'Are you sure you want to delete unit :unit? This action cannot be undone.': 'Uremeza ko ushaka gusiba icyumba :unit? Iki gikorwa ntigishobora gusubirwaho.',
        'Create tenancy': 'Kora ubukode',
        'Create tenancy for :unit': 'Kora ubukode bw’icyumba :unit',
        'Delete Unit': 'Siba icyumba',
        Notes: 'Ibisobanuro',
        'Residential / business address': 'Aderesi yo guturamo / y’akazi',
        'Showing :from to :to of :total units': 'Herekanwa :from kugeza :to kuri :total byumba',
        'Signed lease (PDF, DOC, DOCX, JPG or PNG)': 'Amasezerano yasinywe (PDF, DOC, DOCX, JPG cyangwa PNG)',
        'Tenancy end date': 'Itariki ubukode burangirira',
        'Tenancy start date': 'Itariki ubukode butangirira',
        'Tenant identity, contact information, signed lease, and rent terms are required.': 'Birakenewe umwirondoro n’aho umukodesha abarizwa, amasezerano yasinywe n’amabwiriza y’ubukode.',
        'The first full rent period starts on the tenancy start date.': 'Igihe cya mbere cyuzuye cy’ubukode gitangira ku itariki ubukode butangiriyeho.',
        'Condition / inspection notes': 'Ibisobanuro ku mimerere / igenzura',
        'Deduction explanation': 'Impamvu y’amafaranga yakuweho',
        'Deductions (RWF)': 'Amafaranga yakuweho (RWF)',
        'Deposit received': 'Ingwate yakiriwe',
        'Due day': 'Umunsi wo kwishyura',
        'Move-out date': 'Itariki yo kwimuka',
        'Move-out inspection': 'Igenzura igihe cyo kwimuka',
        'Needs maintenance': 'Ikeneye gusanwa',
        'New lease end': 'Iherezo ry’amasezerano mashya',
        'New lease start': 'Intangiriro y’amasezerano mashya',
        'Record the unit condition and reconcile all received deposits before closing the tenancy.': 'Andika uko icyumba kimeze kandi ugenzure ingwate zose zakiriwe mbere yo gusoza ubukode.',
        'Refund (RWF)': 'Amafaranga asubizwa (RWF)',
        'Save renewal': 'Bika kongera amasezerano',
        'Signed renewal lease': 'Amasezerano mashya yasinywe',
        'Unit after move-out': 'Icyumba nyuma yo kwimuka',
        Deposit: 'Ingwate',
        'Previous agreements remain available for audit and financial history.': 'Amasezerano yabanje aracyaboneka mu igenzura no mu mateka y’amafaranga.',
        'Rent/deposit payments recorded': 'Ubwishyu bw’ubukode/ingwate bwanditswe',
        'Tenancy history': 'Amateka y’ubukode',
        received: 'yakiriwe',
        available: 'kirahari',
        occupied: 'kirimo umukodesha',
        maintenance: 'kirimo gusanwa',
        reserved: 'cyarabitswe',
        inactive: 'ntigikora',
        active: 'kirakora',
        scheduled: 'giteganyijwe',
        ended: 'cyarangiye',
        cancelled: 'cyahagaritswe',
    },
};
