export default {
    fr: {
        'Find your perfect space to rent | Ituze-Qra Ltd': 'Trouvez l’espace idéal à louer | Ituze-Qra Ltd',
        'Location or property name': 'Lieu ou nom du bien',
        Home: 'Accueil',
        Properties: 'Biens',
        'Property types': 'Types de biens',
        Enquiry: 'Demande',
        Inquiry: 'Demande',
        'Log in': 'Connexion',
        Dashboard: 'Tableau de bord',
        'Premium offices in Kigali': 'Bureaux haut de gamme à Kigali',
        'A better address for ambitious teams': 'Une meilleure adresse pour les équipes ambitieuses',
        'From 21,750 RWF / m²': 'À partir de 21 750 RWF / m²',
        'Kacyiru, Kigali': 'Kacyiru, Kigali',
        'Spaces made for business': 'Des espaces conçus pour les entreprises',
        'Move into a workspace that works for you': 'Installez-vous dans un espace adapté à vos besoins',
        'Flexible commercial spaces': 'Espaces commerciaux flexibles',
        'Nyarutarama, Kigali': 'Nyarutarama, Kigali',
        'Beautiful places to grow': 'De beaux espaces pour se développer',
        'Discover offices, shops, cafés and more': 'Découvrez des bureaux, boutiques, cafés et bien plus',
        'Ready-to-rent properties': 'Biens prêts à louer',
        'Kigali, Rwanda': 'Kigali, Rwanda',
        'Offices': 'Bureaux',
        'Apartments': 'Appartements',
        'Coffee Shops': 'Cafés',
        'Commercial Buildings': 'Immeubles commerciaux',
        'Warehouses': 'Entrepôts',
        'Available': 'Disponible',
        'View details': 'Voir les détails',
        'Rental space': 'Espace à louer',
        'Price on request': 'Prix sur demande',
        day: 'jour',
        week: 'semaine',
        month: 'mois',
        quarter: 'trimestre',
        year: 'an',
        'Free enquiry': 'Demande gratuite',
        'Find your next space': 'Trouvez votre prochain espace',
        'Tell us what you are looking for and our property team will contact you.': 'Indiquez-nous ce que vous recherchez et notre équipe immobilière vous contactera.',
        'Your name': 'Votre nom',
        'Phone / WhatsApp': 'Téléphone / WhatsApp',
        'Email (optional)': 'E-mail (facultatif)',
        'What type of space?': 'Quel type d’espace recherchez-vous ?',
        Office: 'Bureau',
        Apartment: 'Appartement',
        'Coffee shop': 'Café',
        'Commercial building': 'Immeuble commercial',
        Warehouse: 'Entrepôt',
        'Describe the space you need...': 'Décrivez l’espace dont vous avez besoin...',
        'Send enquiry': 'Envoyer la demande',
        'Create your account': 'Créez votre compte',
        'Join Ituze-Qra Ltd to manage your property listings.': 'Rejoignez Ituze-Qra Ltd pour gérer vos annonces immobilières.',
        'First name': 'Prénom',
        'Last name': 'Nom',
        'Phone number': 'Numéro de téléphone',
        'Email address': 'Adresse e-mail',
        Location: 'Lieu',
        'Rental Unit': 'Unité à louer',
        'Rental unit': 'Unité à louer',
        'This :type in :location is available for rent. Contact the owner to arrange a viewing and learn more.': 'Ce/cette :type à :location est disponible à la location. Contactez le propriétaire pour organiser une visite et en savoir plus.',
        'this space': 'cet espace',
        'Your message about :space at :property has been sent to the owner.': 'Votre message concernant :space à :property a été envoyé au propriétaire.',
        'Confirm password': 'Confirmer le mot de passe',
        'Creating account...': 'Création du compte...',
        'Create account': 'Créer un compte',
        'Your account will be reviewed before property management access is enabled.': 'Votre compte sera vérifié avant l’activation de l’accès à la gestion immobilière.',
        'Search by location or property name': 'Rechercher par lieu ou nom du bien',
        'All categories': 'Toutes les catégories',
        'All provinces': 'Toutes les provinces',
        'All districts': 'Tous les districts',
        'All sectors': 'Tous les secteurs',
        'Any price': 'Tous les prix',
        'Under 500,000 RWF': 'Moins de 500 000 RWF',
        Search: 'Rechercher',
        'Search results': 'Résultats de recherche',
        ':count available :units found': ':count :units disponibles trouvées',
        unit: 'unité',
        units: 'unités',
        'Clear filters': 'Effacer les filtres',
        'Loading...': 'Chargement...',
        'Load more units': 'Afficher plus d’unités',
        'No matching available units': 'Aucune unité disponible correspondante',
        'Try a different location, property type, or price range.': 'Essayez un autre lieu, type de bien ou niveau de prix.',
        'Available now': 'Disponibles maintenant',
        'Discover Available Rental Units': 'Découvrez les unités à louer',
        'Browse individual spaces, see their details, and contact the property owner.': 'Parcourez les espaces, consultez leurs détails et contactez le propriétaire.',
        'There are no available units yet. Please check back soon.': 'Aucune unité n’est disponible pour le moment. Revenez bientôt.',
        'Explore Our Categories': 'Explorez nos catégories',
        'Choose a category to see available listings.': 'Choisissez une catégorie pour voir les annonces disponibles.',
        'Browse available spaces': 'Parcourir les espaces disponibles',
        'Need help finding a space?': 'Besoin d’aide pour trouver un espace ?',
        'Tell us what you are looking for.': 'Dites-nous ce que vous recherchez.',
        'Our team can help you find an office, apartment, café, commercial building, or warehouse in Kigali.': 'Notre équipe peut vous aider à trouver un bureau, un appartement, un café, un immeuble commercial ou un entrepôt à Kigali.',
        'Start an enquiry': 'Commencer une demande',
        'Talk to Ituze': 'Parlez à Ituze',
        'A smoother way to rent.': 'Louez plus simplement.',
        'No account required to browse': 'Aucun compte nécessaire pour parcourir les annonces',
        'Direct owner enquiries': 'Contact direct avec les propriétaires',
        'WhatsApp-ready communication': 'Communication via WhatsApp',
        'Call us': 'Appelez-nous',
        'Email us': 'Écrivez-nous',
        'Built together': 'Construisons ensemble',
        'Our Partners': 'Nos partenaires',
        'We work with trusted property owners, business communities, relocation teams, and local enterprises to make finding the right space easier.': 'Nous travaillons avec des propriétaires de confiance, des communautés d’affaires, des équipes de relocalisation et des entreprises locales pour faciliter la recherche du bon espace.',
        'Property owners': 'Propriétaires immobiliers',
        'Quality spaces from people who know their properties best.': 'Des espaces de qualité proposés par ceux qui connaissent le mieux leurs biens.',
        'Business communities': 'Communautés d’affaires',
        'Connections that help teams find the right Kigali address.': 'Des contacts qui aident les équipes à trouver la bonne adresse à Kigali.',
        'Relocation teams': 'Équipes de relocalisation',
        'Practical support for people moving into a new space.': 'Un accompagnement pratique pour les personnes qui emménagent.',
        'Local enterprises': 'Entreprises locales',
        'Flexible solutions for growing businesses and brands.': 'Des solutions flexibles pour les entreprises et marques en croissance.',
        'Become a partner': 'Devenir partenaire',
        'Partner with us': 'Devenez partenaire',
        'Let’s work together': 'Travaillons ensemble',
        'Tell us how you would like to work with Ituze-Qra Ltd. Complete the form and our team will contact you.': 'Dites-nous comment vous souhaitez collaborer avec Ituze-Qra Ltd. Remplissez le formulaire et notre équipe vous contactera.',
        'Thank you. Your partner enquiry has been received and our team will contact you soon.': 'Merci. Votre demande de partenariat a été reçue et notre équipe vous contactera bientôt.',
        'Business partnership': 'Partenariat commercial',
        'Call Ituze': 'Appeler Ituze',
        'Chat with Ituze on WhatsApp Web': 'Discuter avec Ituze sur WhatsApp Web',
        'Contact us': 'Contactez-nous',
        'Email Ituze': 'Envoyer un e-mail à Ituze',
        'Featured spaces': 'Espaces à la une',
        'Find us on Google Maps': 'Nous trouver sur Google Maps',
        'For owners': 'Pour les propriétaires',
        'Hello Ituze, I am interested in finding a property for rent.': 'Bonjour Ituze, je souhaite trouver un bien à louer.',
        'How would you like to partner?': 'Comment souhaitez-vous devenir partenaire ?',
        'Ituze-Qra Ltd Logo': 'Logo Ituze-Qra Ltd',
        'Ituze-Qra Ltd location map': 'Carte de localisation d’Ituze-Qra Ltd',
        'List a property': 'Publier un bien',
        'Other partnership': 'Autre partenariat',
        'Owner login': 'Connexion propriétaire',
        'Property categories': 'Catégories de biens',
        'Relocation support': 'Aide à la relocalisation',
        'Send an enquiry': 'Envoyer une demande',
        'Tell us more about your partnership idea...': 'Parlez-nous de votre idée de partenariat...',
        'We received your inquiry!': 'Nous avons reçu votre demande !',
        'The owner will review your details and get back to you as soon as possible, usually within a few minutes.': 'Le propriétaire examinera vos informations et vous répondra dès que possible, généralement en quelques minutes.',
        'Got it': 'Compris',
        'Your contact details were shared with the owner.': 'Vos coordonnées ont été communiquées au propriétaire.',
        'Contact owner': 'Contacter le propriétaire',
        'Private inquiry': 'Demande privée',
        'Let’s get you connected': 'Prenons contact',
        'Send a message directly to the property owner.': 'Envoyez un message directement au propriétaire.',
        'Available rental space': 'Espace disponible à louer',
        'Your message': 'Votre message',
        'Your details are shared only with the property owner.': 'Vos informations ne sont partagées qu’avec le propriétaire.',
        'Sending inquiry...': 'Envoi de la demande...',
        'Send inquiry to owner': 'Envoyer la demande au propriétaire',
        'Property contact': 'Contact du bien',
        'Monthly rent': 'Loyer mensuel',
        'Interested in this space?': 'Cet espace vous intéresse ?',
        'Ask a question or arrange a viewing directly with the owner.': 'Posez une question ou organisez une visite directement avec le propriétaire.',
        'Send a message': 'Envoyer un message',
        'Chat on WhatsApp': 'Discuter sur WhatsApp',
        'WhatsApp unavailable': 'WhatsApp indisponible',
        'Your inquiry goes to the owner dashboard. WhatsApp opens a direct chat with the owner.': 'Votre demande apparaît dans le tableau de bord du propriétaire. WhatsApp ouvre une discussion directe avec lui.',
        'A better way to rent': 'Une meilleure façon de louer',
        'Real spaces. Direct connections.': 'De vrais espaces. Des contacts directs.',
        'Available for rent': 'Disponible à la location',
        Rent: 'Loyer',
        Unit: 'Unité',
        Type: 'Type',
        'Size / Floor': 'Surface / étage',
        Description: 'Description',
        'About this property': 'À propos de ce bien',
        Address: 'Adresse',
        'Open in Google Maps': 'Ouvrir dans Google Maps',
        'Street address': 'Adresse',
        Floor: 'Étage',
        'Not specified': 'Non précisé',
        'Property amenities': 'Équipements du bien',
        'Contact the owner for available facilities and amenities.': 'Contactez le propriétaire pour connaître les installations et équipements disponibles.',
        'Nearby infrastructure': 'Infrastructures à proximité',
        'Strategically located with convenient access to surrounding services.': 'Emplacement stratégique avec un accès pratique aux services à proximité.',
        'Other available units in this property': 'Autres unités disponibles dans ce bien',
        'Available spaces': 'Espaces disponibles',
        'Commercial space': 'Espace commercial',
        'This space': 'Cet espace',
        'Property owner': 'Propriétaire du bien',
        'View photo :number': 'Voir la photo :number',
        'All rights reserved.': 'Tous droits réservés.',
        'Beautiful spaces, better business, and a simpler way to rent in Rwanda.': 'De beaux espaces, de meilleures affaires et une location simplifiée au Rwanda.',
        Explore: 'Explorer',
        'Make an enquiry': 'Faire une demande',
        'rental space': 'espace à louer',
        'Contact this owner': 'Contacter ce propriétaire',
        'Contact Ituze': 'Contacter Ituze',
        'Trusted property listings in Rwanda.': 'Annonces immobilières fiables au Rwanda.',
    },
    rw: {
        'Find your perfect space to rent | Ituze-Qra Ltd': 'Shaka ahantu heza ho gukodesha | Ituze-Qra Ltd',
        Home: 'Ahabanza',
        Properties: 'Inzu',
        'Property types': 'Ubwoko bw’inzu',
        Enquiry: 'Ikibazo',
        Inquiry: 'Ikibazo',
        'Log in': 'Injira',
        Dashboard: 'Imbonerahamwe',
        'Premium offices in Kigali': 'Ibiro byiza cyane i Kigali',
        'A better address for ambitious teams': 'Aderesi nziza ku matsinda afite intego',
        'From 21,750 RWF / m²': 'Kuva kuri 21.750 RWF / m²',
        'Kacyiru, Kigali': 'Kacyiru, Kigali',
        'Spaces made for business': 'Ahantu hagenewe ibikorwa by’ubucuruzi',
        'Move into a workspace that works for you': 'Kodesha ahantu hakubereye gukorera',
        'Flexible commercial spaces': 'Ahantu h’ubucuruzi hatandukanye',
        'Nyarutarama, Kigali': 'Nyarutarama, Kigali',
        'Beautiful places to grow': 'Ahantu heza ho kwagurira ibikorwa',
        'Discover offices, shops, cafés and more': 'Reba ibiro, amaduka, amaresitora n’ibindi',
        'Ready-to-rent properties': 'Inzu ziteguye gukodeshwa',
        'Kigali, Rwanda': 'Kigali, Rwanda',
        Offices: 'Ibiro',
        Apartments: 'Amazu yo kubamo',
        'Coffee Shops': 'Amaresitora',
        'Commercial Buildings': 'Inzu z’ubucuruzi',
        Warehouses: 'Ububiko',
        Available: 'Birahari',
        'View details': 'Reba ibisobanuro',
        'Rental space': 'Ahantu ho gukodesha',
        'Price on request': 'Saba kumenya igiciro',
        day: 'umunsi',
        week: 'icyumweru',
        month: 'ukwezi',
        quarter: 'igihembwe cy’amezi atatu',
        year: 'umwaka',
        'Free enquiry': 'Ikibazo nta kiguzi',
        'Find your next space': 'Shaka ahantu hakubereye',
        'Tell us what you are looking for and our property team will contact you.': 'Tubwire icyo ushaka, itsinda ryacu rirakuvugisha.',
        'Your name': 'Amazina yawe',
        'Phone / WhatsApp': 'Telefoni / WhatsApp',
        'Email (optional)': 'Imeyili (si ngombwa)',
        'What type of space?': 'Urashaka ahantu hameze gute?',
        Office: 'Ibiro',
        Apartment: 'Inzu yo kubamo',
        'Coffee shop': 'Resitora',
        'Commercial building': 'Inzu y’ubucuruzi',
        Warehouse: 'Ububiko',
        'Describe the space you need...': 'Sobanura ahantu ukeneye...',
        'Send enquiry': 'Ohereza ikibazo',
        'Create your account': 'Fungura konti yawe',
        'Join Ituze-Qra Ltd to manage your property listings.': 'Injira muri Ituze-Qra Ltd kugira ngo ucunge inzu zawe.',
        'First name': 'Izina',
        'Last name': 'Izina ry’umuryango',
        'Phone number': 'Nomero ya telefoni',
        'Email address': 'Aderesi ya imeyili',
        Location: 'Ahantu',
        'Rental Unit': 'Icyumba gikodeshwa',
        'Rental unit': 'Icyumba gikodeshwa',
        'This :type in :location is available for rent. Contact the owner to arrange a viewing and learn more.': ':type iri :location rirakodeshwa. Vugana na nyiraryo kugira ngo utegure kurireba umenye byinshi.',
        'this space': 'aha hantu',
        'Your message about :space at :property has been sent to the owner.': 'Ubutumwa bwawe buvuga kuri :space muri :property bwoherejwe kuri nyir’inzu.',
        'Confirm password': 'Emeza ijambo ry’ibanga',
        'Creating account...': 'Turimo gukora konti...',
        'Create account': 'Fungura konti',
        'Your account will be reviewed before property management access is enabled.': 'Konti yawe izabanza kugenzurwa mbere yo kwemererwa gucunga inzu.',
        'Location or property name': 'Ahantu cyangwa izina ry’inzu',
        'Search by location or property name': 'Shakisha ahantu cyangwa izina ry’inzu',
        'All categories': 'Ibyiciro byose',
        'All provinces': 'Intara zose',
        'All districts': 'Uturere twose',
        'All sectors': 'Imirenge yose',
        'Any price': 'Igiciro cyose',
        'Under 500,000 RWF': 'Munsi ya 500.000 RWF',
        Search: 'Shakisha',
        'Search results': 'Ibyavuye mu gushakisha',
        ':count available :units found': 'Habonetse :count :units zihari',
        unit: 'icyumba',
        units: 'ibyumba',
        'Clear filters': 'Siba ibyo wahisemo',
        'Loading...': 'Biratunganywa...',
        'Load more units': 'Reba ibindi byumba',
        'No matching available units': 'Nta byumba bihari bihuye n’ ibyo washakishije',
        'Try a different location, property type, or price range.': 'Gerageza ahandi, ubundi bwoko bw’inzu cyangwa igiciro.',
        'Available now': 'Birahari ubu',
        'Discover Available Rental Units': 'Reba ibyumba bihari byo gukodesha',
        'Browse individual spaces, see their details, and contact the property owner.': 'Reba ibyumba, usome ibisobanuro, uvugane na nyir’inzu.',
        'There are no available units yet. Please check back soon.': 'Nta byumba bihari ubu. Ongera urebe nyuma.',
        'Explore Our Categories': 'Reba ibyiciro byacu',
        'Choose a category to see available listings.': 'Hitamo icyiciro kugira ngo urebe inzu zihari.',
        'Browse available spaces': 'Reba ahantu hahari',
        'Need help finding a space?': 'Ukeneye ubufasha bwo gushaka ahantu?',
        'Tell us what you are looking for.': 'Tubwire icyo ushaka.',
        'Our team can help you find an office, apartment, café, commercial building, or warehouse in Kigali.': 'Itsinda ryacu ryagufasha kubona ibiro, inzu yo kubamo, resitora, inzu y’ubucuruzi cyangwa ububiko i Kigali.',
        'Start an enquiry': 'Tangira kubaza',
        'Talk to Ituze': 'Vugana na Ituze',
        'A smoother way to rent.': 'Uburyo bworoshye bwo gukodesha.',
        'No account required to browse': 'Nta konti ikenewe kugira ngo urebe inzu',
        'Direct owner enquiries': 'Vugana na nyir’inzu',
        'WhatsApp-ready communication': 'Vugana ukoresheje WhatsApp',
        'Call us': 'Duhamagare',
        'Email us': 'Twandikire kuri imeyili',
        'Built together': 'Dukorana twese',
        'Our Partners': 'Abafatanyabikorwa bacu',
        'We work with trusted property owners, business communities, relocation teams, and local enterprises to make finding the right space easier.': 'Dukorana na ba nyir’inzu bizewe, abacuruzi, abafasha abantu kwimuka n’ibigo byo mu gihugu kugira ngo byorohe kubona ahantu hakwiye.',
        'Property owners': 'Ba nyir’inzu',
        'Quality spaces from people who know their properties best.': 'Ahantu heza hatanzwe na ba nyiraho babizi neza.',
        'Business communities': 'Amatsinda y’abacuruzi',
        'Connections that help teams find the right Kigali address.': 'Ubufatanye bufasha kubona aderesi ikwiye i Kigali.',
        'Relocation teams': 'Abafasha kwimuka',
        'Practical support for people moving into a new space.': 'Ubufasha ku bantu bimukira ahandi.',
        'Local enterprises': 'Ibigo byo mu gihugu',
        'Flexible solutions for growing businesses and brands.': 'Ibisubizo byoroshye ku bucuruzi buri kwaguka.',
        'Become a partner': 'Ba umufatanyabikorwa',
        'Partner with us': 'Dukorane',
        'Let’s work together': 'Dukorane',
        'Tell us how you would like to work with Ituze-Qra Ltd. Complete the form and our team will contact you.': 'Tubwire uko wifuza gukorana na Ituze-Qra Ltd. Uzuza iyi fomu, itsinda ryacu rirakuvugisha.',
        'Thank you. Your partner enquiry has been received and our team will contact you soon.': 'Murakoze. Twakiriye ubutumwa bwanyu kandi itsinda ryacu rizabavugisha vuba.',
        'Business partnership': 'Ubufatanye mu bucuruzi',
        'Call Ituze': 'Hamagara Ituze',
        'Chat with Ituze on WhatsApp Web': 'Vugana na Ituze kuri WhatsApp Web',
        'Contact us': 'Twandikire',
        'Email Ituze': 'Ohereza imeyili kuri Ituze',
        'Featured spaces': 'Ahantu hagaragara',
        'Find us on Google Maps': 'Dushakire kuri Google Maps',
        'For owners': 'Ba nyir’inzu',
        'Hello Ituze, I am interested in finding a property for rent.': 'Muraho Ituze, nifuza kubona inzu yo gukodesha.',
        'How would you like to partner?': 'Wifuza gukorana natwe mu buhe buryo?',
        'Ituze-Qra Ltd Logo': 'Ikirango cya Ituze-Qra Ltd',
        'Ituze-Qra Ltd location map': 'Ikarita y’aho Ituze-Qra Ltd iherereye',
        'List a property': 'Shyira inzu ku rubuga',
        'Other partnership': 'Ubundi bufatanye',
        'Owner login': 'Kwinjira kwa nyir’inzu',
        'Property categories': 'Ibyiciro by’inzu',
        'Relocation support': 'Ubufasha bwo kwimuka',
        'Send an enquiry': 'Ohereza ikibazo',
        'Tell us more about your partnership idea...': 'Tubwire birambuye igitekerezo cyawe cy’ubufatanye...',
        'We received your inquiry!': 'Twakiriye ubutumwa bwawe!',
        'The owner will review your details and get back to you as soon as possible, usually within a few minutes.': 'Nyir’inzu azasoma amakuru yawe agusubize vuba bishoboka, akenshi mu minota mike.',
        'Got it': 'Ndabyumvise',
        'Your contact details were shared with the owner.': 'Amakuru yawe y’itumanaho yagejejwe kuri nyir’inzu.',
        'Contact owner': 'Vugana na nyir’inzu',
        'Private inquiry': 'Ubutumwa bwihariye',
        'Let’s get you connected': 'Reka tugufashe kuvugana na nyir’inzu',
        'Send a message directly to the property owner.': 'Ohereza ubutumwa kuri nyir’inzu.',
        'Available rental space': 'Ahantu hahari ho gukodesha',
        'Your message': 'Ubutumwa bwawe',
        'Your details are shared only with the property owner.': 'Amakuru yawe ahabwa nyir’inzu gusa.',
        'Sending inquiry...': 'Turimo kohereza ubutumwa...',
        'Send inquiry to owner': 'Ohereza ubutumwa kuri nyir’inzu',
        'Property contact': 'Itumanaho rya nyir’inzu',
        'Monthly rent': 'Ubukode bw’ukwezi',
        'Interested in this space?': 'Ushishikajwe n’aha hantu?',
        'Ask a question or arrange a viewing directly with the owner.': 'Baza ikibazo cyangwa utegure kureba inzu uvugana na nyirayo.',
        'Send a message': 'Ohereza ubutumwa',
        'Chat on WhatsApp': 'Vugana kuri WhatsApp',
        'WhatsApp unavailable': 'WhatsApp ntiboneka',
        'Your inquiry goes to the owner dashboard. WhatsApp opens a direct chat with the owner.': 'Ubutumwa bwawe bujya kuri nyir’inzu. WhatsApp ifungura ikiganiro na nyir’inzu.',
        'A better way to rent': 'Uburyo bwiza bwo gukodesha',
        'Real spaces. Direct connections.': 'Ahantu nyaho. Ubufatanye butaziguye.',
        'Available for rent': 'Harakodeshwa',
        Rent: 'Ubukode',
        Unit: 'Icyumba',
        Type: 'Ubwoko',
        'Size / Floor': 'Ingano / Igorofa',
        Description: 'Ibisobanuro',
        'About this property': 'Ibyerekeye iyi nzu',
        Address: 'Aderesi',
        'Open in Google Maps': 'Fungura kuri Google Maps',
        'Street address': 'Aderesi y’umuhanda',
        Floor: 'Igorofa',
        'Not specified': 'Ntabwo byasobanuwe',
        'Property amenities': 'Ibikoresho byo muri iyi nzu',
        'Contact the owner for available facilities and amenities.': 'Vugana na nyir’inzu umenye ibiyirimo n’ibikoresho bihari.',
        'Nearby infrastructure': 'Ibikorwaremezo biri hafi',
        'Strategically located with convenient access to surrounding services.': 'Iherereye ahantu heza hafi y’izindi serivisi.',
        'Other available units in this property': 'Ibindi byumba bihari muri iyi nzu',
        'Commercial space': 'Ahantu h’ubucuruzi',
        'This space': 'Aha hantu',
        'Property owner': 'Nyir’inzu',
        'View photo :number': 'Reba ifoto :number',
        'All rights reserved.': 'Uburenganzira bwose burabitswe.',
        'Beautiful spaces, better business, and a simpler way to rent in Rwanda.': 'Ahantu heza, ubucuruzi bwiza n’uburyo bworoshye bwo gukodesha mu Rwanda.',
        Explore: 'Reba',
        'Make an enquiry': 'Ohereza ikibazo',
        'rental space': 'ahantu ho gukodesha',
        'Available spaces': 'Ahantu hahari',
        'Contact this owner': 'Vugana na nyir’iyi nzu',
        'Contact Ituze': 'Vugana na Ituze',
        'Trusted property listings in Rwanda.': 'Inzu zo mu Rwanda zizewe.',
    },
};
